prisma/prisma1

docs/04-Reference/06-Auth/02-Authentication/02-Authentication-Tokens.md

change word reqeusts to requests in the first paragraph

Correct a typo in 02-Authentication-Tokens.md docs

---

cli/packages/graphcool-cli-core/src/commands/init/index.test.ts

Related to https://github.com/graphcool/graphcool/commit/f45a228437ec480fbd45830331b30f2f1f32cef5

Disabling template on init broke tests

---

cli/packages/graphcool-cli-engine/src/ProjectDefinition/ProjectDefinition.ts

Support linebreaks in require/import statements

---

examples/rest-wrapper/package.json

Added package.json

---

docs/02-Concepts/01-Overview/01-The-Graphcool-Framework.md
docs/02-Concepts/01-Overview/02-Platform-Overview.md

happier docs

---

docs/04-Reference/08-Deployment/01-Overview.md

Fixed count of local machines

---

cli/packages/graphcool-cli-core/src/examples.ts

Indent list elements in initial yml file (fix #828)

---

cli/packages/graphcool-cli-core/src/commands/root-token/index.ts

Changed wording project -> service

---

cli/packages/graphcool-cli-engine/src/Client/Client.ts
server/backend-shared/src/main/scala/cool/graph/shared/errors/Errors.scala

Fixes #909. 
Updated error message in system API + updated string-based check for that error in CLI.

Wording: no project with id -> no service with id

---

docs/03-Tutorials/02-Auth/02-Authentication-with-Email-and-Password-for-React-&-Apollo.md

Updated inline variables -> graphql variables

---

server/backend-shared/src/main/scala/cool/graph/shared/models/Function.scala

Something like this would result in a generic could not parse schema extension error.
```graphql
type GetStuffPayload {
bool: [Boolean]
}
extend type Query {
startBattle( ): GetStuffPayload!
}
```
We will now return the hint that empty brackets are not allowed for resolvers without input arguments.

Introduce specific error if resolver definition contains unnecessary brackets

---

docs/04-Reference/05-Functions/04-Subscriptions.md

Update `operation_in` to `mutation_in` to conform to the latest subscription api.

Update 04-Subscriptions.md to use updated filter terminology

---

server/single-server/src/main/scala/cool/graph/singleserver/SingleServerDependencies.scala

Works around a complex evaluation order bug with the latest version of the code.

Lazify single server deps

---

docs/03-Tutorials/01-Functions/02-Subscription-Functions.md

I just found one small typo in DOCs...

Typo in tutorial DOCs fixed

---

docs/04-Reference/05-Functions/02-Runtime-Environment.md

Fixed one typo

---

server/single-server/src/main/scala/cool/graph/singleserver/SingleServerDependencies.scala

Change GlobalDatabaseManager initialization as it isn't suited to init asynchronously at the moment.

Single server initialization fixes

---

docs/04-Reference/05-Functions/01-Overview.md

I could be mistaken, but this looks to me like it was a copy/paste error

Fix error in Function Overview document

---

cli/packages/graphcool-cli-core/src/commands/delete/index.ts

As a temporary user-friendly fix for #1008

Added guard for delete local similar to console local

---

cli/packages/graphcool-cli-core/src/commands/add-template/add-template.ts

Remove temp folder after add-template

---

examples/node-gateway-custom-schema/README.md
examples/rest-wrapper/types.graphql

Outdated docs links

---

server/backend-shared/src/main/scala/cool/graph/shared/functions/EndpointResolver.scala

Updated protocol for local subscriptions endpoint

---

docs/04-Reference/01-Service-Definition/03-Deploying-Services.md
server/backend-api-system/src/main/scala/cool/graph/system/migration/dataSchema/validation/SchemaErrors.scala

Fixes #1066.
Updated in docs and system API error message.

#1066 - Update all usage information according to diff/--dry-run change

---

docs/03-Tutorials/02-Auth/02-Authentication-with-Email-and-Password-for-React-&-Apollo.md

Updates apollo imports to the more modular 2.0 packages. Updates code to new typescript templates. Fixes various typos.

Update doc to be Apollo Client 2.0 compliant.

---

cli/packages/graphcool-cli-engine/src/ProjectDefinition/yaml.ts

Do not merge directly. This PR depends on:
If `graphcool-json-schema` is published with that PR, the version needs to be updated in this PR before merging to keep things consistent.

[WIP] Upgraded schema to draft-06

---

server/backend-shared/src/main/scala/cool/graph/client/database/DatabaseMutationBuilder.scala
server/backend-shared/src/main/scala/cool/graph/client/database/SlickExtensions.scala
server/client-shared/src/main/scala/cool/graph/client/mutactions/ImportNodesInBulk.scala
server/client-shared/src/main/scala/cool/graph/client/server/ClientServer.scala
server/client-shared/src/main/scala/cool/graph/client/server/RequestHandler.scala

This is the beginning of the work to implement the bulk data import endpoint sketched out in https://github.com/graphcool/framework/issues/1299

[WIP] Bulk Data Import Endpoint

---

server/client-shared/src/main/scala/cool/graph/client/mutactions/ImportExport.scala
server/client-shared/src/main/scala/cool/graph/client/mutactions/ImportNodesInBulk.scala
server/client-shared/src/main/scala/cool/graph/client/server/RequestHandler.scala

Improvement of the error messages

[WIP] Data import2

---

server/api/src/main/scala/cool/graph/api/server/ApiServer.scala
server/deploy/src/main/scala/cool/graph/deploy/schema/fields/AddProjectField.scala
server/deploy/src/main/scala/cool/graph/deploy/schema/fields/DeployField.scala
server/deploy/src/main/scala/cool/graph/deploy/schema/mutations/AddProjectMutation.scala
server/deploy/src/main/scala/cool/graph/deploy/schema/mutations/DeployMutation.scala
server/shared-models/src/main/scala/cool/graph/shared/models/Models.scala
server/shared-models/src/main/scala/cool/graph/shared/models/ProjectJsonFormatter.scala

This introduces the ability to set secrets for a service-stage an validates generated jwts before processing any queries or mutations

Graphql database service auth

---

docs/01-Quickstart/01-Frontend/03-Vue/01-Apollo.md

`CreatePage` should be `CreatePost`

Correct CreatePost component name in 01-Apollo.md

---

docs/03-Tutorials/02-Auth/02-Authentication-with-Email-and-Password-for-React-&-Apollo.md

I found a small mistake in docs.

fix example which can't work on authenticate react tutorial

---

docs/04-Reference/02-Graphcool-CLI/02-Commands.md

Update Command docs to remove export reference

---

server/backend-shared/src/main/scala/cool/graph/Utils.scala
server/backend-shared/src/main/scala/cool/graph/client/database/DataResolver.scala
server/backend-shared/src/main/scala/cool/graph/client/database/DatabaseQueryBuilder.scala
server/backend-shared/src/main/scala/cool/graph/client/database/ProjectDataresolver.scala
server/backend-shared/src/main/scala/cool/graph/shared/models/Models.scala
server/client-shared/src/main/scala/cool/graph/client/mutactions/ImportExport.scala
server/client-shared/src/main/scala/cool/graph/client/mutactions/ServerSideSubscription.scala
server/client-shared/src/main/scala/cool/graph/client/requestPipeline/RequestPipelineRunner.scala
server/libs/javascript-engine/src/main/scala/cool/graph/javascriptEngine/JavascriptExecutor.scala

Beginning of the work to implement the export part of https://github.com/graphcool/framework/issues/1299

[WIP] Export Bulk Data

---

server/client-shared/src/main/scala/cool/graph/client/ImportExport/BulkExport.scala

If the CLI requests nodes, relations or lists for a project that is missing one of them we were blowing up. Also fixes an error when optional Listfields contain null.

Fix internal error when exporting project

---

server/client-shared/src/main/scala/cool/graph/client/ImportExport/BulkExport.scala
server/client-shared/src/main/scala/cool/graph/client/ImportExport/BulkImport.scala

make sure DateTime is in Iso8601 format in the NDF

Date time changes for export import

---

docs/0.x/04-Reference/02-Graphcool-CLI/02-Commands.md

This PR fixes a simple typo in the documentation :)

Fix typo in documentation

---

server/client-shared/src/main/scala/cool/graph/client/ImportExport/BulkExport.scala
server/client-shared/src/main/scala/cool/graph/client/ImportExport/BulkImport.scala
server/client-shared/src/main/scala/cool/graph/client/ImportExport/package.scala

also improve handling of listvalues

Add support for optional backrelations to Import

---

docs/0.x/04-Reference/01-Service-Definition/03-Deploying-Services.md

Just fixing a small mistake I found while reading through the docs.

Add missing subject in deploying services doc

---

cli/packages/graphcool-cli-core/src/commands/console/index.ts
cli/packages/graphcool-cli-core/src/commands/init/index.ts

This PR fixes a couple of typos.

CLI wording

---

server/deploy/src/main/scala/cool/graph/deploy/DeployDependencies.scala
server/deploy/src/main/scala/cool/graph/deploy/migration/MigrationStepMapper.scala
server/deploy/src/main/scala/cool/graph/deploy/schema/Errors.scala
server/deploy/src/main/scala/cool/graph/deploy/schema/SchemaBuilder.scala
server/deploy/src/main/scala/cool/graph/deploy/server/ClusterAuth.scala
server/deploy/src/test/scala/cool/graph/deploy/ClusterAuthSpec.scala
server/deploy/src/test/scala/cool/graph/deploy/migration/inference/InfererIntegrationSpec.scala
server/deploy/src/test/scala/cool/graph/deploy/migration/inference/MigrationStepsInferrerSpec.scala
server/deploy/src/test/scala/cool/graph/deploy/migration/inference/SchemaInfererSpec.scala
server/deploy/src/test/scala/cool/graph/deploy/migration/migrator/MigrationApplierSpec.scala
server/deploy/src/test/scala/cool/graph/deploy/migration/validation/SchemaSyntaxValidatorSpec.scala
server/deploy/src/test/scala/cool/graph/deploy/specutils/DeployTestDependencies.scala
server/single-server/src/main/scala/cool/graph/singleserver/SingleServerDependencies.scala

Added auth to all mutations and queries.

[1.0] Basic deploy authentication

---

examples/auth/.graphqlconfig.yml
examples/auth/README.md
examples/auth/database/graphcool.yml
examples/auth/graphcool.yml
examples/auth/package.json
examples/auth/src/generated/graphcool.graphql
examples/auth/src/index.js
examples/auth/yarn.lock

Upgrade auth example to graphcool 1.0.0-beta4.1.1

Examples 1.0

---

server/libs/metrics/src/main/scala/cool/graph/metrics/MetricsManager.scala

- Adjustments to underlying metrics lib

[1.0] Database metric basics

---

docs/1.0/03-Tutorials/04-Cluster-Deployment/02-Digital-Ocean-(Docker-Machine).md

Hi guys and girls 👋 
thanks for your work, it looks awesome 😄 
I noticed a typo reading the documentation so I fixed it in this PR.
Thank you, can't wait to try prisma in a new project 👍

Fix typo on "Connect to Digital Ocean" section

---

docs/1.0/04-Reference/02-Prisma-API/02-Concepts.md

But let's check back with @sorenbs before we settle on the wording.

Remarks about transactionality are outdated

---

server/api/src/main/scala/com/prisma/api/database/DatabaseMutationBuilder.scala
server/api/src/main/scala/com/prisma/api/database/DatabaseQueryBuilder.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/AddDataItemToManyRelationByUniqueField.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/CreateDataItem.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/RemoveDataItemFromManyRelationByToId.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/RemoveDataItemFromManyRelationByUniqueField.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/UpsertDataItem.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/UpsertDataItemIfInRelationWith.scala
server/api/src/main/scala/com/prisma/api/mutations/SqlMutactions.scala
server/api/src/main/scala/com/prisma/api/mutations/mutations/Upsert.scala
server/api/src/test/scala/com/prisma/api/mutations/NestedUpsertMutationInsideUpdateSpec.scala
server/api/src/test/scala/com/prisma/api/mutations/RelationDesignSpec.scala
server/api/src/test/scala/com/prisma/api/mutations/UpsertDesignSpec.scala

- nested mutations in upserts are still not enabled, this will follow in a later PR

Enable Scalar Lists in Upsert

---

server/deploy/src/main/scala/com/prisma/deploy/migration/validation/SchemaSyntaxValidator.scala
server/deploy/src/test/scala/com/prisma/deploy/database/schema/mutations/DeployMutationSpec.scala

fix for https://github.com/graphcool/prisma/issues/1703

Relation Directives on Self Relation Bugs

---

server/api/src/main/scala/com/prisma/api/database/DatabaseMutationBuilder.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/NestedConnectRelationMutaction.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/NestedCreateRelationMutaction.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/NestedDeleteRelationMutaction.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/NestedDisconnectRelationMutaction.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/NestedRelationMutactionBaseClass.scala
server/api/src/main/scala/com/prisma/api/mutations/SqlMutactions.scala
server/api/src/main/scala/com/prisma/api/schema/Errors.scala
server/api/src/test/scala/com/prisma/api/mutations/NestedConnectMutationInsideCreateSpec.scala
server/api/src/test/scala/com/prisma/api/mutations/NestedConnectMutationInsideUpdateSpec.scala
server/api/src/test/scala/com/prisma/api/mutations/NestedCreateMutationInsideCreateSpec.scala
server/api/src/test/scala/com/prisma/api/mutations/NestedCreateMutationInsideUpdateSpec.scala
server/api/src/test/scala/com/prisma/api/mutations/NestedDeleteMutationInsideUpdateSpec.scala
server/api/src/test/scala/com/prisma/api/mutations/NestedDisconnectMutationInsideUpdateSpec.scala
server/api/src/test/scala/com/prisma/api/mutations/RelationGraphQLSpec.scala

- fix for:
--  nested create inside update
--  nested create inside create
--  nested delete inside update 
-- also checks other relations on the child that might be violated by a delete

[WIP] Required Relations and Removal from Relations Fix pt 2

---

server/api/src/main/scala/com/prisma/api/database/import_export/BulkImport.scala
server/api/src/test/scala/com/prisma/api/import_export/ImportJsonFormatSpec.scala
server/api/src/test/scala/com/prisma/api/import_export/ListValueImportExportSpec.scala
server/api/src/test/scala/com/prisma/api/import_export/SingleValueImportExportSpec.scala

Convert json after parsing it and before writing it to DB
Activate additional tests for json format

Fix Json handling in import and export

---

server/api/src/main/scala/com/prisma/api/database/DatabaseMutationBuilder.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/SetScalarListToEmpty.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/UpsertDataItemIfInRelationWith.scala
server/api/src/main/scala/com/prisma/api/mutations/SqlMutactions.scala
server/api/src/test/scala/com/prisma/api/mutations/UpsertDesignSpec.scala
server/api/src/test/scala/com/prisma/api/queries/ScalarListsQuerySpec.scala

Enables resetting scalar lists to empty with '{set : []}'
fixes https://github.com/graphcool/prisma/issues/1706

Enable resetting scalarlists to empty

---

server/api/src/main/scala/com/prisma/api/database/DatabaseMutationBuilder.scala
server/api/src/main/scala/com/prisma/api/mutations/SqlMutactions.scala
server/api/src/test/scala/com/prisma/api/queries/ScalarListsQuerySpec.scala

Fix for https://github.com/graphcool/prisma/issues/1803
list members on different positions than the new ones being set were not deleted
add tests

Delete all old list members on set

---

docs/1.1/03-Tutorials/03-Database/02-Database-Access-(SQL).md

I wasn't able to log into my local docker container msyql until I searched the code and found the correct password.

fix mysql password typo

---

server/api/src/main/scala/com/prisma/api/database/DatabaseMutationBuilder.scala

Cannot currently upsert reliably as the keys and values returned for the create are sometimes out of order

Upsert arguments are always in order resolves #1761

---

server/api/src/main/scala/com/prisma/api/database/DatabaseMutationBuilder.scala
server/api/src/test/scala/com/prisma/api/mutations/UpsertMutationSpec.scala

Added test cases for upsert fix

---

docs/1.1/03-Tutorials/04-Cluster-Deployment/04-Kubernetes.md

Moved my Kubernetes tutorial from https://github.com/akoenig/graphcool-prisma-kubernetes-deployment :)

docs: adds a tutorial about how to deploy a Prisma database to Kubernetes

---

docs/1.1/03-Tutorials/04-Cluster-Deployment/04-Kubernetes.md

big shoutout to @akoenig for contributing this tutorial, and @delta98 for review and feedback 🙌

Kubernetes tutorial

---

docs/1.0/03-Tutorials/02-GraphQL-Server-Development/03-Permissions.md

Added missing userId definition.

Fixed post resolver in permission example

---

docs/1.1/03-Tutorials/04-Cluster-Deployment/01-Digital-Ocean-(Docker-Machine).md

The compute instances are called Droplets on DO :)

docs: fix typo in DO documentation

---

server/api/src/main/scala/com/prisma/api/mutations/CoolArgs.scala
server/api/src/test/scala/com/prisma/api/mutations/UpdateMutationSpec.scala

fix for https://github.com/graphcool/prisma/issues/1848

Enable updating an optional value to reset it to null

---

docs/1.0/04-Reference/04-Clusters/01-Overview.md
docs/1.1/04-Reference/05-Clusters/01-Overview.md

Closes https://github.com/graphcool/prisma/issues/1861
Please let me know if any changes are needed.

docs: add a note on logout in cluster references 1.0, 1.1

---

server/build.sbt
server/deploy/src/main/scala/com/prisma/deploy/DeployDependencies.scala
server/deploy/src/main/scala/com/prisma/deploy/schema/SchemaBuilder.scala
server/deploy/src/test/scala/com/prisma/deploy/database/schema/queries/GenerateProjectTokenSpec.scala
server/deploy/src/test/scala/com/prisma/deploy/specutils/DeploySpecBase.scala
server/deploy/src/test/scala/com/prisma/deploy/specutils/DeployTestDependencies.scala
server/libs/auth/src/main/scala/com/prisma/auth/Auth.scala
server/libs/auth/src/test/scala/com/prisma/auth/AuthSpec.scala
server/single-server/src/main/scala/com/prisma/singleserver/SingleServerDependencies.scala

- this PR also fixes the bug that we did not check the expiration of tokens so far.

implement generateProjectToken Query

---

docs/1.1/04-Reference/06-Data-Import-&-Export/01-Data-Import.md

I guess, this is just a documentation fix and will close #1873

docs: add the correct data directory flag

---

server/api/src/main/scala/com/prisma/api/database/DatabaseMutationBuilder.scala
server/api/src/main/scala/com/prisma/api/database/DatabaseQueryBuilder.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/DeleteRelationMutaction.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/NestedRelationMutactionBaseClass.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/UpsertDataItemIfInRelationWith.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/VerifyConnection.scala
server/api/src/main/scala/com/prisma/api/mutations/SqlMutactions.scala
server/api/src/main/scala/com/prisma/api/mutations/mutations/CascadingDeletes.scala
server/api/src/test/scala/com/prisma/api/mutations/CascadingDeletePathSpec.scala
server/api/src/test/scala/com/prisma/api/mutations/NestedDisconnectMutationInsideUpdateSpec.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Models.scala

Self-relations would sometimes error since relation.sideOf(model) returns wrong results for self relations.
Fix for: https://github.com/graphcool/prisma/issues/1609

Self relation problems in Nested Connect

---

docs/1.2/03-Tutorials/04-Cluster-Deployment/03-Digital-Ocean-(manual).md

Specify that both docker and docker compose are needed and share link for docker compose installation

Improve documentation

---

cli/packages/prisma-cli-core/src/commands/local/stop.ts

fix(cli): fix `prisma local stop` message

---

server/api/src/main/scala/com/prisma/api/server/ApiServer.scala
server/deploy/src/main/scala/com/prisma/deploy/DeployDependencies.scala
server/deploy/src/main/scala/com/prisma/deploy/schema/mutations/DeployMutation.scala
server/deploy/src/main/scala/com/prisma/deploy/schema/mutations/FunctionValidator.scala
server/deploy/src/test/scala/com/prisma/deploy/database/schema/mutations/DeployMutationSpec.scala
server/deploy/src/test/scala/com/prisma/deploy/specutils/DeployTestDependencies.scala
server/images/prisma-local/src/main/scala/com/prisma/local/FunctionValidatorImpl.scala
server/images/prisma-local/src/main/scala/com/prisma/local/PrismaLocalDependencies.scala
server/images/prisma-prod/src/main/scala/com/prisma/prod/FunctionValidatorImpl.scala
server/images/prisma-prod/src/main/scala/com/prisma/prod/PrismaProdDependencies.scala

Fixes https://github.com/graphcool/prisma/issues/1922

Errors when deploying subscription queries with activated auth

---

server/api/src/main/scala/com/prisma/api/database/DatabaseMutationBuilder.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/CascadingDeleteRelationMutactions.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/DeleteRelationMutaction.scala
server/api/src/main/scala/com/prisma/api/mutations/mutations/CascadingDeletes.scala
server/api/src/test/scala/com/prisma/api/mutations/DeleteMutationRelationsSpec.scala

make sure to check if the node is required even if it has no backrelation field

Required relation checks on optional backrelations

---

server/servers/deploy/src/main/scala/com/prisma/deploy/schema/Errors.scala

Update error for invalid relation name #2046

---

server/servers/deploy/src/main/scala/com/prisma/deploy/schema/Errors.scala

fix test broken as a result of https://github.com/graphcool/prisma/pull/2073

Fix test broken by relation error message fix from johan

---

cli/README.md
cli/packages/prisma-cli-core/README.md
cli/packages/prisma-cli-engine/README.md
cli/packages/prisma-cli/README.md
cli/packages/prisma-yml/README.md

A little update for the README inside the `cli/` folder and which is use for the npm package page.
(like just a ctrl+c/v of the README at the root of the repository 😉)

Update cli/README.md for npm package page

---

server/servers/api/src/main/resources/application.conf

Fixes https://github.com/graphcool/prisma/issues/2024

Set import max content length to 50mb

---

server/servers/api/src/main/scala/com/prisma/api/ApiDependencies.scala
server/servers/api/src/main/scala/com/prisma/api/import_export/BulkExport.scala

- 10mb chunks sometimes took more than 300sec when being imported and timed out

Reduce export chunksize to 1mb

---

server/servers/deploy/src/main/scala/com/prisma/deploy/schema/mutations/DeleteProjectMutation.scala

Update error for invalid service to delete #2076

---

cli/packages/prisma-cli-core/src/commands/console/index.ts

Opening console in web fixes #2038

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/DataResolverImpl.scala
server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/DatabaseMutationBuilder.scala
server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/DatabaseQueryBuilder.scala
server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/SlickExtensions.scala
server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/impl/DatabaseMutactionInterpreters.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/ApiMutaction.scala
server/servers/api/src/main/scala/com/prisma/api/mutactions/DatabaseMutactions.scala
server/servers/api/src/main/scala/com/prisma/api/mutations/DeleteMany.scala
server/servers/api/src/main/scala/com/prisma/api/mutations/UpdateMany.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/CountManyModelDeferredResolver.scala
server/servers/api/src/main/scala/com/prisma/api/schema/ArgumentsBuilder.scala
server/servers/api/src/main/scala/com/prisma/api/schema/InputTypesBuilder.scala
server/servers/api/src/main/scala/com/prisma/api/schema/SchemaBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/DeleteManyRelationFilterSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/UpdateManyRelationFilterSpec.scala
server/servers/api/src/test/scala/com/prisma/api/schema/MutationsSchemaBuilderSpec.scala

Fixes 
https://github.com/graphcool/prisma/issues/2085
https://github.com/graphcool/prisma/issues/2039
https://github.com/graphcool/prisma/issues/2140

Make where filter optional on updateMany and deleteMany

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/DatabaseQueryBuilder.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/Path.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/IntegrationBaseSpec.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/SeveralRelationsBetweenSameModelsIntegrationSpec.scala
server/servers/api/src/test/scala/com/prisma/api/ApiTestServer.scala
server/servers/api/src/test/scala/com/prisma/api/import_export/OptionalBackRelationImportExportSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/DeeplyNestedSelfRelationSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/ManyToManySelfRelationSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/SameFieldSameModelRelationSpec.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/SchemaMapper.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/inference/MigrationStepsInferrer.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/inference/SchemaInferrer.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/inference/SchemaMapping.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/inference/UnambiguousRelation.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/database/schema/mutations/DeployMutationSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/database/schema/mutations/SeveralRelationsBetweenSameModelsSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/specutils/DeploySpecBase.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/specutils/DeployTestServer.scala
server/servers/deploy/src/test/scala/com/prisma/shared/schema_dsl/SchemaDsl.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Models.scala

Fixes https://github.com/graphcool/prisma/issues/2124

More than two relations between models produce errors

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/DatabaseQueryBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/import_export/OptionalBackRelationImportExportSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/ManyToManySelfRelationSpec.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Models.scala

Fixes https://github.com/graphcool/prisma/issues/2188

Fix a bug where sameField sameModel relations were incorrectly resolved

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/DatabaseQueryBuilder.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/Path.scala
server/servers/api/src/test/scala/com/prisma/api/ApiTestServer.scala
server/servers/api/src/test/scala/com/prisma/api/import_export/OptionalBackRelationImportExportSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/DeeplyNestedSelfRelationSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/ManyToManySelfRelationSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/SameFieldSameModelRelationSpec.scala
server/servers/deploy/src/test/scala/com/prisma/shared/schema_dsl/SchemaDsl.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Models.scala

Fixes https://github.com/graphcool/prisma/issues/2089

Deeply nested self relations not executed

---

cli/packages/prisma-cli-engine/src/Output/migration.ts

Pull request to fix the issue #2057

fix(cli): update output for DeleteModele action

---

docs/1.6/01-Quickstart/02-Fullstack/01-React/01-Apollo.md

```
type Post
implements Node {
id: ID!
isPublished: Boolean!
title: String!
text: String!
}
```

example has incorrect fields on queries

---

server/servers/api/src/main/scala/com/prisma/api/server/ApiServer.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/ClusterServer.scala

Makes it easier to distinguish request IDs.

Add environment info to request Id

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/QueryArgumentsHelpers.scala
server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/SlickExtensions.scala
server/servers/api/src/main/scala/com/prisma/api/schema/FilterArguments.scala
server/servers/api/src/main/scala/com/prisma/api/schema/ObjectTypeBuilder.scala
server/servers/api/src/main/scala/com/prisma/api/schema/SchemaBuilderUtils.scala
server/servers/api/src/test/scala/com/prisma/api/filters/FilterSpec.scala

According to issue about adding NOT filter, I would like to try to contribute this project.
Review and every comment would be most welcome. My first PR, I hope that not last :)
PR is related to issue #1852

Added NOT filter

---

cli/packages/prisma-cli-core/src/commands/deploy/index.ts

remove outdated help text for deploy command

---

server/servers/api/src/main/scala/com/prisma/subscriptions/SubscriptionExecutor.scala
server/servers/api/src/main/scala/com/prisma/subscriptions/schema/QueryTransformer.scala
server/servers/api/src/main/scala/com/prisma/subscriptions/schema/VariablesTransformer.scala
server/servers/api/src/test/scala/com/prisma/api/queries/ValidateSubscriptionQuerySpec.scala
server/servers/api/src/test/scala/com/prisma/api/schema/TransformVariablesSpec.scala

Fixes certain where filters not working when passed in as variables.
https://github.com/graphcool/prisma/issues/1734

Replace reserved filters in variables json

---

docs/1.7/04-Reference/05-Prisma-Servers-&-DBs/01-Prisma-Servers/02-Docker.md

[Docs] Fix to PRISMA_CONFIG environment at docker-compose.yml example

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/Databases.scala
server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/database/Databases.scala
server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/InternalDatabaseDefs.scala
server/connectors/deploy-connector-postgresql/src/main/scala/com/prisma/deploy/connector/postgresql/InternalDatabaseDefs.scala

Fixes https://github.com/graphcool/prisma/issues/2290

Fix quoting for db users and passwords across connectors

---

docs/1.7/04-Reference/09-Upgrade-Guides/02-Upgrading-Prisma/01-Overview.md

Update 01-Overview.md - Fix Typo

---

server/build.sbt
server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/MySqlApiConnector.scala
server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/DatabaseQueryBuilder.scala
server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/Databases.scala
server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/MySqlDataResolver.scala
server/images/prisma-local/src/main/scala/com/prisma/local/PrismaLocalDependencies.scala
server/servers/api/src/main/scala/com/prisma/api/project/CachedProjectFetcherImpl.scala
server/servers/api/src/main/scala/com/prisma/api/project/ProjectFetcherImpl.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/CountToManyDeferredResolver.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/DeferredResolverProvider.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/ManyModelDeferredResolver.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/ManyModelExistsDeferredResolver.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/OneDeferredResolver.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/ScalarListDeferredResolver.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/ToManyDeferredResolver.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/ToOneDeferredResolver.scala
server/servers/api/src/main/scala/com/prisma/api/schema/ObjectTypeBuilder.scala
server/servers/api/src/main/scala/com/prisma/api/server/ApiServer.scala

Use less aggressive logging by default

Prisma logging changes

---

server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/SchemaErrors.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/SchemaSyntaxValidator.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/migration/validation/SchemaSyntaxValidatorSpec.scala

also remove @model directive from tests
and @migrationValue from directiveDefinitions
Fixes https://github.com/graphcool/prisma/issues/2172

Validate that all enums have unique names

---

server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/database/PostgresApiDatabaseMutationBuilder.scala
server/connectors/deploy-connector-postgresql/src/main/scala/com/prisma/deploy/connector/postgresql/database/PostgresDeployDatabaseMutationBuilder.scala

Fixes https://github.com/graphcool/prisma/issues/2351

Make raise_exception function schema specific

---

server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/database/PostgresApiDatabaseMutationBuilder.scala
server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/impl/PostgresDatabaseMutactionExecutor.scala
server/connectors/deploy-connector-postgresql/src/main/scala/com/prisma/deploy/connector/postgresql/database/Telemetry.scala

Fixes https://github.com/graphcool/prisma/issues/2396

Make sure to use the Postgres Profile in the Postgres Connector

---

server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/DeployingDefaultValuesSpec.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/SchemaErrors.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/SchemaSyntaxValidator.scala

add deploy and default value tests

Check that the defaultValue on enum fields is a proper enum value

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/Databases.scala
server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/database/Databases.scala

- Correct quoting for api connector configs.

1.8.3 fixes

---

server/servers/api/src/test/scala/com/prisma/api/ApiTestServer.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/InsertingNullInRequiredFieldsSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/OptionalBackrelationSpec.scala

- for setting optional values to null

Add test cases 

---

docs/1.8/04-Reference/02-Service-Configuration/03-Data-Model/01-Data-Modelling-(SDL).md

This should help users googling or using CTRL+F on the page.

Docs: Correct error language for adding required field

---

cli/packages/prisma-cli-core/LICENSE
cli/packages/prisma-cli-engine/LICENSE
cli/packages/prisma-cli/LICENSE
cli/packages/prisma-db-introspection/LICENSE
cli/packages/prisma-yml/LICENSE

This is very important.
:unicorn: 
Thank you.

:bug: Add missing license to packages

---

docs/1.8/03-Tutorials2/04-Connect-to-Prisma-from-the-frontend.md

This tutorial focuses on content mainly. I could have added more screenshots and maybe an initial GIF that shows how the final app looks like. Let me know if you'd prefer the tutorial to have more visual content and I'd happily add it.
I should have added a button on Quickstart that links to this tutorial, but I could not find the Quickstart file that links to the tutorials (The one that corresponds to https://www.prisma.io/docs/quickstart/). I saw it in previous versions of the docs, but not on 1.8.
I will happily receive any kind of feedback for this tutorial 😄

Write tutorial "Connect to Prisma from the frontend"

---

cli/packages/prisma-db-introspection/src/Introspector.ts
cli/packages/prisma-db-introspection/src/SdlPrinter.ts
cli/packages/prisma-db-introspection/src/connectors/PostgresConnector.ts
cli/packages/prisma-db-introspection/src/tests/postgres/__snapshots__/largeSchema.test.ts.snap
cli/packages/prisma-db-introspection/src/tests/postgres/__snapshots__/relations.test.ts.snap
cli/packages/prisma-db-introspection/src/tests/postgres/__snapshots__/scalars.test.ts.snap
cli/packages/prisma-db-introspection/src/tests/postgres/largeSchema.test.ts
cli/packages/prisma-db-introspection/src/tests/postgres/scalars.test.ts
cli/packages/prisma-db-introspection/src/types/common.ts
cli/packages/prisma-db-introspection/tsconfig.json

Changed ID generation to conform to Prisma standard.
Bugfixed type generation for unknown types.
Fixed ordering.
Fixed primary key detection.

First wave of PostgreSQL introspection changes

---

server/.buildkite/pipeline.sh
server/.buildkite/scripts/docker-build.sh
server/.buildkite/scripts/stable.sh
server/.buildkite/scripts/test.sh
server/.buildkite/scripts/unstable.sh

Implements: https://www.prisma.io/blog/improving-prismas-release-process-yaey8deiwaex/

New release process pipeline

---

cli/packages/prisma-cli-core/src/commands/seed/Seeder.ts

Fixed typo in `cross-spawn` import

fix: prisma seed via run

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/MySqlApiDatabaseMutationBuilder.scala
server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/database/PostgresApiDatabaseMutationBuilder.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/schema/Errors.scala
server/servers/api/src/main/scala/com/prisma/api/mutactions/DatabaseMutactions.scala
server/servers/api/src/main/scala/com/prisma/util/coolArgs/GcConverters.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/SettingNodeSelectorToNullSpec.scala

Fixes https://github.com/prismagraphql/prisma/issues/2426

Handle null when updating node selector

---

.circleci/config.yml
cli/packages/prisma-cli-core/package.json
cli/packages/prisma-cli-core/src/commands/account/account.ts
cli/packages/prisma-cli-core/src/commands/delete/index.ts
cli/packages/prisma-cli-core/src/commands/deploy/index.ts
cli/packages/prisma-cli-core/src/commands/import/Validator.ts
cli/packages/prisma-cli-core/src/commands/seed/Seeder.ts
cli/packages/prisma-cli-core/src/commands/seed/seed.ts
cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts
cli/packages/prisma-cli-engine/src/Client/Client.ts
cli/packages/prisma-cli-engine/src/Output/index.ts
cli/packages/prisma-cli-engine/src/StatusChecker.ts
cli/packages/prisma-yml/README.md
cli/packages/prisma-yml/src/Cluster.ts
cli/packages/prisma-yml/src/Environment.ts
cli/packages/prisma-yml/src/PrismaDefinition.ts
cli/scripts/make-notes.sh
cli/scripts/publish.sh
cli/scripts/release-template.ejs
cli/yarn.lock

This PR merges the changes from the beta branch into the master branch.

Release 1.9

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/MySqlApiDatabaseQueryBuilder.scala
server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/database/ClauseBuilders.scala
server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/database/PostgresApiDatabaseQueryBuilder.scala
server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/database/QueryBuilders.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/DataResolverTypes.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/ToManyDeferredResolver.scala
server/servers/api/src/main/scala/com/prisma/api/schema/ObjectTypeBuilder.scala
server/servers/api/src/main/scala/com/prisma/api/schema/SangriaQueryArguments.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/NestedConnectMutationInsideUpdateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/queries/OrderBySpec.scala
server/servers/api/src/test/scala/com/prisma/api/queries/PaginationSpec.scala

Fixes a bug in the Postgres OrderBy
Improves the performance of fetching related nodes when using pagination

Batch select from related improvements

---

cli/packages/prisma-cli-core/src/commands/import/Importer.ts

Fixes https://github.com/prismagraphql/prisma/issues/2165

fix: catch errors and clean up .import

---

cli/packages/prisma-cli-engine/src/Config.ts

Fixes https://github.com/prismagraphql/prisma/issues/2637

add .yaml to possible list of graphql config file names

---

docs/1.8/03-Tutorials2/06-Deploy-Prisma-Servers/04-Kubernetes.md

This PR contains the updated tutorial on how to deploy Prisma `>= 1.8` to Kubernetes.

docs: adds updated tutorial for deploying Prisma > 1.8 to Kubernetes

---

cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts

Fixes https://github.com/prismagraphql/prisma/issues/2708

Fix endpoint bug with prisma deploy

---

cli/packages/prisma-cli-engine/src/Client/Client.ts

This change fixed my issue: https://github.com/prismagraphql/prisma/issues/2592

Prevent unhandled promise rejection on opening browser window

---

cli/packages/prisma-cli-core/src/commands/console/index.ts

I haven't really run into this issue but I can imagine I'd happen aswell as described here: https://github.com/prismagraphql/prisma/issues/2592
I'm sorry for making 4 PRs (lazily using github webui) but I hope it helps :+1:

Prevent unhandled rejection error

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/MySqlDatabasesFactory.scala
server/connectors/api-connector-postgres/src/main/scala/com/prisma/api/connector/postgres/PostgresDatabasesFactory.scala
server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/MySqlDeployConnector.scala
server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/MysqlInternalDatabaseDefs.scala
server/connectors/deploy-connector-mysql/src/test/scala/com/prisma/deploy/connector/mysql/InternalTestDatabase.scala
server/connectors/deploy-connector-mysql/src/test/scala/com/prisma/deploy/connector/mysql/SpecBase.scala
server/connectors/deploy-connector-postgres/src/main/scala/com/prisma/deploy/connector/postgres/PostgresDeployConnector.scala
server/connectors/deploy-connector-postgres/src/main/scala/com/prisma/deploy/connector/postgres/PostgresInternalDatabaseDefs.scala
server/connectors/deploy-connector-postgres/src/test/scala/com/prisma/deploy/connector/postgres/InternalTestDatabase.scala
server/connectors/deploy-connector-postgres/src/test/scala/com/prisma/deploy/connector/postgres/SpecBase.scala
server/images/prisma-local/src/main/scala/com/prisma/local/PrismaLocalDependencies.scala
server/images/prisma-prod/src/main/scala/com/prisma/prod/PrismaProdDependencies.scala
server/libs/prisma-config/src/main/scala/com/prisma/config/ConfigLoader.scala
server/libs/prisma-config/src/test/scala/com/prisma/auth/ConfigLoaderSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/PassiveConnectorSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/specutils/DeploySpecBase.scala

Prisma was not correctly obeying the setting for connection limit in the server config. Prisma was actually acquiring around 10 times the number of connections specified. This PR fixes it.
fixes:
https://github.com/prismagraphql/prisma/issues/2680
https://github.com/prismagraphql/prisma/issues/2640

fix connection limit setting

---

cli/packages/prisma-yml/src/Environment.ts
cli/packages/prisma-yml/src/PrismaDefinition.ts

Fixes https://github.com/prismagraphql/prisma/issues/2668

fix: do not allow usage of cluster, service properties together

---

cli/packages/prisma-cli-core/src/commands/delete/index.ts

Fixes https://github.com/prismagraphql/prisma/issues/2017

fix: include server name in delete command

---

cli/packages/prisma-cli-core/src/commands/import/Importer.ts
cli/packages/prisma-cli-core/src/commands/import/Validator.ts

Fixes https://github.com/prismagraphql/prisma/issues/2006

fix: validate NDF folder structure

---

docs/1.10/03-Tutorials2/01-Setup-Prisma/03-Connect-Empty-DB/02-Postgres.md

Probably this should be an alias, but I have no idea how the docs get build.
Let me know if I can do it better! I couldn't really find it in the contribution guidelines.

Updated localhost to prisma.io for link.

---

docs/1.11/04-Reference/02-Service-Configuration/03-Data-Model/02-Migrations.md

I do like the word "bigrations" though

fix: typo bigrations -> migrations

---

docs/1.9/03-Tutorials2/02-Build-GraphQL-Servers/01-Development/01-Build-a-GraphQL-Server-with-Prisma.md

data object shows content: args.title
should be content: args.content

Update createDraft Mutation resolver

---

cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts

Fixes https://github.com/prismagraphql/prisma/issues/2413

fix: introspection input - don't ask for schemaName when no data

---

cli/packages/prisma-cli-core/src/commands/logout/logout.ts
cli/packages/prisma-cli-core/src/index.ts
cli/packages/prisma-cli-engine/src/Client/Client.ts
cli/scripts/build.sh

Fixes #1870, also added build script.

Adds Logout command

---

server/CONTRIBUTING.md
server/servers/api/src/test/scala/com/prisma/api/queries/JsonVariablesSpec.scala

This is an update on #2664. The previous one is stale. @mavilein

Moving it to different branch as earlier one got stale #2664

---

server/libs/sangria-utils/src/main/scala/com/prisma/sangria/utils/ErrorHandler.scala
server/servers/api/src/main/scala/com/prisma/api/ApiDependencies.scala
server/servers/api/src/main/scala/com/prisma/api/server/GraphQlRequestHandler.scala
server/servers/api/src/main/scala/com/prisma/api/server/RequestHandler.scala
server/servers/api/src/main/scala/com/prisma/api/server/RequestLifecycle.scala
server/servers/api/src/main/scala/com/prisma/api/server/package.scala
server/servers/api/src/main/scala/com/prisma/subscriptions/SubscriptionExecutor.scala
server/servers/api/src/test/scala/com/prisma/api/server/RequestHandlerSpec.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/ManagementServer.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/specutils/DeployTestServer.scala

set up caches for query parsing and validation

Cache some of the sangria work

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/RelationActions.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/ValidationActions.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/impl/CreateNodeInterpreters.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/impl/DeleteNodeInterpreters.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/impl/NestedConnectInterpreter.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/impl/NestedDisconnectInterpreter.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/impl/UpdateNodeInterpreters.scala
server/servers/api/src/main/scala/com/prisma/api/mutactions/DatabaseMutactions.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/NestedConnectMutationInsideCreateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/NestedConnectMutationInsideUpdateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/NestedDeleteMutationInsideUpdateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/NestedDisconnectMutationInsideUpdateSpec.scala

Fixes https://github.com/prismagraphql/prisma/issues/2810

ManyToMany Self Relations Bug on Disconnect

---

cli/packages/prisma-cli-core/src/commands/seed/Seeder.ts

Fixes issue with reseting when using 'run' as seed definition

---

cli/packages/prisma-cli-core/src/commands/init/index.ts

Tested the existing functionality. Tested the `--endpoint` flag with and without a directory name. 
Fixes https://github.com/prismagraphql/prisma/issues/2838

feat: add --endpoint to init

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/FilterConditionBuilder.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/SetParams.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/DataResolverTypes.scala
server/servers/api/src/main/scala/com/prisma/api/schema/ObjectTypeBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/filters/FilterSpec.scala

Fixes an error where an empty logical filter like AND, OR, NOT would error

Empty logical filters bug

---

docs/1.13/03-Tutorials2/06-Deploy-Prisma-Servers/07-Dokku.md

Added an tutorial for deploying a prisma server to dokku with postgres as backing service.

Add deploy to dokku tutorial

---

cli/packages/prisma-cli-core/src/commands/playground/index.ts

Fixes #2763.
Cleaned up some unneeded code.

assume web flag if port is passed into playground command

---

cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts

fix: update default suggestions for prisma init

---

docs/1.13/04-Reference/02-Service-Configuration/03-Data-Model/01-Data-Modelling-(SDL).md

Fix minor typo in docs -> Data Modelling reference

docs: Typo @uniue -> @unique

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/NodeManyQueries.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/impl/JdbcDataResolver.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/DataResolver.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/DataResolverTypes.scala
server/servers/api/src/main/scala/com/prisma/api/mutations/DeleteMany.scala
server/servers/api/src/main/scala/com/prisma/api/mutations/UpdateMany.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/CountManyModelDeferredResolver.scala
server/servers/api/src/test/scala/com/prisma/api/queries/AggregationQuerySpec.scala

fix issue 2897

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/QueryBuilderConstants.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/RelatedModelsQueryBuilder.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/ResultSetReaders.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Field.scala

Fix issue 2786

---

server/project/Dependencies.scala
server/servers/api/src/main/scala/com/prisma/api/schema/FilterOutEmptyInputTypes.scala
server/servers/api/src/main/scala/com/prisma/api/schema/InputTypesBuilder.scala
server/servers/api/src/main/scala/com/prisma/api/schema/SchemaBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/schema/InputTypesSchemaBuilderSpec.scala

fix issue 3011

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/LimitClauseBuilder.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/NodeManyQueries.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/RelatedModelsQueryBuilder.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/RelationQueries.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/ScalarListQueries.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/SetParams.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/CursorConditionBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/FilterConditionBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/OrderByClauseBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/extensions/MongoExtensions.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/impl/MongoDataResolver.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/helpers/LimitClauseHelper.scala
server/servers/api/src/test/scala/com/prisma/api/queries/OrderBySpec.scala
server/servers/api/src/test/scala/com/prisma/api/queries/embedded/EmbeddedPaginationSpec.scala
server/servers/api/src/test/scala/com/prisma/api/queries/nonEmbedded/NonEmbeddedOrderBySpec.scala
server/servers/api/src/test/scala/com/prisma/api/queries/nonEmbedded/NonEmbeddedPaginationSpec.scala

* move common pagination logic into the core
* start implementing pagination for Mongo

 Mongo Pagination

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/RelatedModelsQueryBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/queries/ExtendedPaginationSpec.scala

Fixes https://github.com/prisma/prisma/issues/3120
Fixes https://github.com/prisma/prisma/pull/3127

Postgres Pagination Bug for nested Items

---

cli/packages/prisma-generate-schema/src/index.ts

client: sort types before generating CRUD schema

---

docs/1.17/get-started/01-setting-up-prisma-demo-server-a001.mdx
docs/1.17/get-started/01-setting-up-prisma-existing-database-a003.mdx
docs/1.17/get-started/01-setting-up-prisma-new-database-a002.mdx
docs/1.17/get-started/02-change-data-model-c001.mdx
docs/1.17/get-started/03-build-graphql-servers-with-prisma-e001.mdx
docs/1.17/get-started/03-build-rest-apis-with-prisma-e002.mdx
docs/1.17/get-started/04-explore-features-f001.mdx

This seems to break the order of the getting started tutorials. @timsuchanek could you take a look please before merging this?

Added tech selector

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/NodeManyQueries.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/DataResolverTypes.scala
server/servers/api/src/test/scala/com/prisma/api/queries/OrderByInMutationSpec.scala
server/servers/api/src/test/scala/com/prisma/api/queries/OrderBySpec.scala

because queries with pagination might fail otherwise
Fixes https://github.com/prisma/prisma/issues/3040
Fixes https://github.com/prisma/prisma/issues/3092

Add the orderBy field to the selected set in Postgres

---

cli/packages/prisma-cli-core/src/commands/deploy/deploy.ts
cli/packages/prisma-cli-core/src/commands/seed/seed.ts

Fixes https://github.com/prisma/prisma/issues/3131
1. Seeding while deploy shows the warning and ends with a success exit code "0"
2. Seeding with seed command throws an error and ends with failure exit code "1"

fix(seed): handle invalid yml

---

docs/1.17/data-model-and-migrations/data-model-knul.mdx

Fix typos in docs

---

client/src/Client.ts

Fixes https://github.com/prisma/prisma/issues/3174

fix(client): enum support

---

cli/packages/prisma-cli-core/package.json
cli/packages/prisma-cli-core/src/commands/generate/generate.ts
cli/yarn.lock

Fixes https://github.com/prisma/prisma/issues/3192

fix(client): env interpolation

---

cli/packages/prisma-cli-core/src/commands/generate/generate.ts
client/src/codegen/typescript-client.ts

Fixes https://github.com/prisma/prisma/issues/3184
1. - [x] Add `--endpoint` flag
1. - [ ] Add `--endpoint <url>` flag (tracked via https://github.com/prisma/prisma/issues/3206)
1. - [x] Handle `executeRaw` mutation field (also consider - https://github.com/prisma/prisma/issues/3185)

feat(schema-generation): bypass js generator via flag

---

client/src/Client.ts

Fixes https://github.com/prisma/prisma/issues/3226

fix(client): make connections lazy

---

cli/packages/prisma-cli-engine/src/Config.ts

Fixes: https://github.com/prisma/prisma/issues/3250

feat(cli): detect prisma.yml additionally in prisma folder

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/NodeActions.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/impl/DeleteNodeInterpreters.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/nonEmbedded/VeryManyMutationsSpec.scala

Fixes https://github.com/prisma/prisma/issues/2953

Cascading delete parameter limit

---

cli/packages/prisma-cli-core/src/commands/init/index.ts
cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts

don't write docker-compose.yml for demo server, only ask for docker-compose if needed

---

server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/SchemaSyntaxValidator.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/migration/validation/SchemaSyntaxValidatorSpec.scala

Fix issue #2871: make schema validation more resilient

---

client/src/Client.ts

BREAKING: remove explicit where wrapper for subscriptions in Prisma client

---

cli/packages/prisma-cli-core/src/commands/generate/generate.ts
client/src/codegen/go-client.ts

Add auth support for Prisma service protected with a secret.

fix(go): add auth

---

client/src/Client.ts

Fixes https://github.com/prisma/prisma/issues/3293

fix(client): add $graphql implementation to JS based clients

---

docs/1.18/understand-prisma/prisma-introduction-what-why-how-j9ff.mdx

There is a bug where is written "thius" i've changed to "this"

Update "thius" to "this"

---

server/servers/api/src/main/scala/com/prisma/api/schema/ObjectTypeBuilder.scala
server/servers/api/src/main/scala/com/prisma/api/schema/OutputTypesBuilder.scala
server/servers/api/src/main/scala/com/prisma/api/schema/SchemaBuilder.scala
server/servers/api/src/main/scala/com/prisma/subscriptions/schema/SubscriptionDataResolver.scala
server/servers/api/src/main/scala/com/prisma/subscriptions/schema/SubscriptionSchema.scala
server/servers/api/src/test/scala/com/prisma/api/schema/EmbeddedTypesSchemaBuilderSpec.scala

add @embedded to embedded types on the schema

Mongo Schema Adjustments

---

server/servers/api/src/main/scala/com/prisma/api/schema/ObjectTypeBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/queries/embedded/EmbeddedPaginationSpec.scala
server/servers/api/src/test/scala/com/prisma/api/schema/EmbeddedTypesSchemaBuilderSpec.scala

remove queryArguments from relations to embedded types until they are implemented

Remove queryarguments from nested relation to embedded types

---

server/servers/api/src/main/scala/com/prisma/api/resolver/IdBasedConnection.scala
server/servers/api/src/main/scala/com/prisma/api/schema/SangriaQueryArguments.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/inference/SchemaInferrer.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/DataModelValidatorImpl.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Model.scala
server/shared-models/src/main/scala/com/prisma/shared/models/ReservedFields.scala

.. and name hidden id field for embedded types in mongo _id

Do not add id fields to nonembedded types in Mongo

---

cli/README.md

doc: Update README.md

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/MongoApiConnector.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/MongoDatabasesFactory.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/MongoDeployConnector.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/MongoInternalDatabaseDefs.scala

* enable ssl
* enable mongo+srv connection string for mongo atlas

Mongo Connection String

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/MongoApiConnector.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/MongoDatabasesFactory.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/impl/MongoDataResolver.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/impl/MongoDatabaseMutactionExecutor.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/MongoDeployConnector.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/MongoInternalDatabaseDefs.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/impl/MongoClientDbQueries.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/impl/MongoDeployMutactionExecutor.scala
server/libs/prisma-config/src/main/scala/com/prisma/config/ConfigLoader.scala

* use database as name when creating dbs
* parse authSource for authentication source

Mongo Enable AuthSource and DB

---

server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/database/MongoDeployDatabaseMutationBuilder.scala
server/connectors/utils/src/main/scala/com/prisma/connectors/utils/ConnectorUtils.scala

only create collections if they do not exist yet,
do not drop collections or fields when they are remove from the data model

Mongo Deploy behaviour

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/CursorConditionBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/FilterConditionBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeActions.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeManyQueries.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeSingleQueries.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/extensions/MongoExtensions.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/schema/Errors.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/MongoInternalDatabaseDefs.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/DeleteMutationSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/UpsertMutationSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/nonEmbedded/nestedMutations/NestedConnectMutationInsideCreateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/nonEmbedded/nestedMutations/NestedConnectMutationInsideUpsertSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/nonEmbedded/nestedMutations/NestedUpdateMutationInsideUpdateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/nonEmbedded/nestedMutations/NestedUpsertMutationInsideUpdateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/queries/MongoObjectIdSpec.scala
server/servers/api/src/test/scala/com/prisma/api/queries/NodeQuerySpec.scala
server/servers/api/src/test/scala/com/prisma/api/queries/ScalarListsQuerySpec.scala
server/servers/api/src/test/scala/com/prisma/api/queries/SingleItemQuerySpec.scala

* store the ids as type Object id to enable reading from pre-existing collections

Mongo object ids

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/RelationActions.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/MongoPrototypingSpec.scala

Mongo do not connect nodes more than once

---

docs/1.20/understand-prisma/prisma-introduction-what-why-how-j9ff.mdx

Fix a small typo in the *Clean and layered architecture section*

Fix Typo (thius to this)

---

docs/1.20/prisma-cli-and-configuration/data-import-and-export-jsw9.mdx

Documentation has the wrong `prisma export` flags.

Correct export flags

---

docs/1.19/run-prisma-server/deployment-environments/docker-rty1.mdx

Ref:
- https://github.com/prismagraphql/prisma/issues/2394
- https://stackoverflow.com/questions/52591611/specifying-prismas-database-name-in-postgresql

Add database properties

---

server/.buildkite/scripts/docker-test-setups/docker-compose.test.mongo.yml
server/build.sbt
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/MongoDatabasesFactory.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/MongoInternalDatabaseDefs.scala
server/docker-compose/mongo/prisma.yml
server/libs/prisma-config/src/main/scala/com/prisma/config/ConfigLoader.scala

* reduce setup to database and uri string

Switch Mongo Connection String Again

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/ImportActions.scala
server/servers/api/src/main/scala/com/prisma/api/import_export/BulkImport.scala
server/servers/api/src/test/scala/com/prisma/api/import_export/ListValueImportExportSpec.scala

Fixes https://github.com/prisma/prisma/issues/3550

Fix a bug when importing ListValues

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/impl/CreateNodeInterpreters.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/FilterConditionBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeActions.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeManyQueries.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeSingleQueries.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/OrderByClauseBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/RelationActions.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/ValidationActions.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/extensions/MongoExtensions.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/impl/CreateNodeInterpreters.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/PathExtension.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/PrismaNode.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/impl/mutactions/ColumnMutactionInterpreters.scala
server/libs/gc-values/src/main/scala/com/prisma/gc_values/GcValues.scala
server/servers/api/src/main/scala/com/prisma/api/schema/ObjectTypeBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/nestedMutations/nonEmbeddedToEmbedded/EmbeddedNestedUpdateManyMutationInsideUpdateSpec.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Field.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Model.scala

* always use dbName to write to Mongo and name when returning data
* Fixes https://github.com/prisma/Mongo-Connector-Preview/issues/11

Mongo @db fixes

---

client/package.json
client/src/Client.ts

Fix relay connection

---

server/servers/api/src/main/scala/com/prisma/api/schema/ObjectTypeBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/filters/nonEmbedded/FilterUnwrapSomeSpec.scala

Fixes https://github.com/prisma/prisma/issues/3662

Fix a bug in the Filter Parsing

---

cli/packages/prisma-cli-core/src/commands/generate/generate.ts
cli/packages/prisma-cli-core/src/commands/init/index.ts

Fixes https://github.com/prisma/prisma/issues/3458

fix(brew): native spawn for binary

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/CustomUpdateCombiner.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/FilterConditionBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/DeleteManyOnEmbeddedBug3662Spec.scala

* add test case for deleteMany on embedded
* handle $in as special case

DeleteMany on Embedded Bug

---

server/servers/api/src/test/scala/com/prisma/api/filters/PortedFiltersSpec.scala

* there are different filter engines depending on whether a relation to a non-embedded type is included or not

Test the aggregation framework filter path on Mongo as well 

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/AggregationQueryBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeManyQueries.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeSingleQueries.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/OrderByClauseBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/ProjectionBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/ValidationActions.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/MongoFilterPerformanceSpec.scala
server/shared-models/src/main/scala/com/prisma/shared/models/ReservedFields.scala

* introduce ProjectionBuilder
* start limiting the SelectionSet where possible,
* we can't actually apply the set everywhere yet since the nested fields are still missing

Selected fields improvements for Mongo

---

server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/database/MongoDeployDatabaseMutationBuilder.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/impl/mutactions/RelationMutactionInterpreters.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/MongoFilterPerformanceSpec.scala

* fixes a bug where we were creating indexes on embedded types and not on embedded ids

Mongo embedded index bug

---

docs/1.23/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4.mdx

Changed "JavsScript" to "JavaScript"

Fix spelling mistake

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/extensions/JdbcExtensions.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/UUIDCreateGraphQLSpec.scala

Fix uuid null pointer exception in ResultSetExtension.

---

server/servers/api/src/main/scala/com/prisma/api/schema/FilterArguments.scala
server/servers/api/src/test/scala/com/prisma/api/filters/nonEmbedded/UUIDFilterSpec.scala

Fix missing UUID in where clause.

---

cli/packages/prisma-cli-engine/src/Client/Client.ts
cli/packages/prisma-cli-engine/src/Client/types.ts

Fixes https://github.com/prisma/prisma/issues/2980

feat(login): show account information while login

---

cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts
cli/packages/prisma-cli-engine/src/Client/Client.ts

Do not show unnecessary meta "requires login" when already logged in.
Fixes https://github.com/prisma/prisma/issues/3667

fix(login): better messaging

---

cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts

fixes https://github.com/prisma/prisma/issues/3180

feat(service): better default name selection

---

cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts

Fixes https://github.com/prisma/prisma/issues/3749

fix(mongo): use datamodel v2 in new mongo workflow

---

cli/packages/prisma-cli-core/src/commands/deploy/deploy.ts

Fixes https://github.com/prisma/prisma/issues/3909

fix(deploy): check migration steps for backward compatability

---

server/servers/api/src/main/scala/com/prisma/api/resolver/DeferredTypes.scala
server/servers/api/src/main/scala/com/prisma/api/resolver/ToOneDeferredResolver.scala
server/servers/api/src/main/scala/com/prisma/api/schema/ObjectTypeBuilder.scala

Fixes https://github.com/prisma/prisma/issues/3981

Use selected fields from context for ToOneDeferreds

---

cli/packages/prisma-client-lib/src/codegen/generators/go-client.ts

Include enum types in field list

---

cli/packages/prisma-client-lib/src/codegen/generators/go-client.ts

Ensure consistent spelling of type names

---

cli/packages/prisma-cli-core/src/commands/deploy/deploy.ts
cli/packages/prisma-cli-engine/src/Client/Client.ts
cli/packages/prisma-cli-engine/src/Command.ts
cli/packages/prisma-cli-engine/src/Output/StreamOutput.ts
cli/packages/prisma-cli-engine/src/Output/actions/SimpleAction.ts
cli/packages/prisma-cli-engine/src/Output/actions/SpinnerAction.ts

Fixes https://github.com/prisma/prisma/issues/3977

fix(deploy): do not write to stderr in non-error condition

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/MiscQueries.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/ExecuteRawSpec.scala

Execute raw aliasing for MySQL

---

cli/packages/prisma-cli-core/src/commands/generate/generate.ts

Fixes https://github.com/prisma/prisma/issues/3584

fix(generate): add success message to graphql-schema generation

---

docs/1.9/05-FAQ/02-Technical.md

I added the FAQ Question: "Does Prisma Cloud come with a built-in Database?" to the Technical section of the FAQ.
I think this is a common misconception for beginners, who tend to use the demo server and expect things to work the same on their own servers.

Added FAQ Question: Does Prisma Cloud come with a built-in Database?

---

docs/1.19/prisma-graphql-api/prisma-bindings/prisma-bindings-prb1.mdx
docs/1.19/prisma-graphql-api/prisma-bindings/reference-prb2.mdx

replace `schemaPath` with `typeDefs`

Minor fixes to docs

---

docs/1.20/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4.mdx

Missing word
and is 'the' foundation

Grammatical Fix

---

docs/1.15/develop-prisma-service/service-configuration/data-model-knul.mdx
docs/1.20/data-model-and-migrations/data-model-knul.mdx

The text should refer to Boolean and not to Float, I suspect it was a copy-paste omission to change from Float to Boolean.

minor edits

---

docs/1.22/datamodel-and-migrations/datamodel-MYSQL-knul.mdx

This page has a broken internal link. Here's a fix.

Update link: #graphql-directives → #sdl-directives

---

cli/packages/prisma-cli-core/src/commands/generate/generate.ts

Fixes https://github.com/prisma/prisma/issues/3359

[BREAKING] fix(generate): emit GraphQL schema to a single file

---

cli/packages/prisma-cli-core/src/commands/delete/index.ts
cli/packages/prisma-cli-core/src/commands/deploy/deploy.ts
cli/packages/prisma-cli-core/src/commands/export/index.ts
cli/packages/prisma-cli-core/src/commands/generate/generate.ts
cli/packages/prisma-cli-core/src/commands/import/index.ts
cli/packages/prisma-cli-core/src/commands/info/index.ts
cli/packages/prisma-cli-core/src/commands/introspect/introspect.ts
cli/packages/prisma-cli-core/src/commands/playground/index.ts
cli/packages/prisma-cli-core/src/commands/reset/reset.ts
cli/packages/prisma-cli-core/src/commands/seed/seed.ts
cli/packages/prisma-cli-core/src/commands/token/cluster-token.ts
cli/packages/prisma-cli-core/src/commands/token/token.ts
cli/packages/prisma-yml/src/PrismaDefinition.ts

Fixes https://github.com/prisma/prisma/issues/3140

feat(project): add --project for Prisma definition file selection

---

server/connectors/deploy-connector-jdbc/src/main/scala/com/prisma/deploy/connector/jdbc/persistence/JdbcProjectPersistence.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/database/MongoDeployDatabaseMutationBuilder.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/impl/MongoProjectPersistence.scala
server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/database/MysqlJdbcDeployDatabaseMutationBuilder.scala
server/connectors/deploy-connector-postgres/src/main/scala/com/prisma/deploy/connector/postgres/database/PostgresJdbcDeployDatabaseMutationBuilder.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/schema/mutations/AddProjectMutation.scala
server/servers/deploy/src/test/scala/com/prisma/shared/schema_dsl/SchemaDsl.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Project.scala

Fixes https://github.com/prisma/prisma/issues/4086 https://github.com/prisma/prisma/issues/4076

Create a schema using the project.dbName instead of the id

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/CursorConditionBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/queries/nonEmbedded/NonEmbeddedPaginationSpec.scala

Fixes https://github.com/prisma/prisma/issues/4093

Postgres cursor bug

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/CursorConditionBuilder.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/OrderByClauseBuilder.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/SetParams.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/AggregationQueryBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/CursorConditionBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeManyQueries.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/OrderByClauseBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/queries/PaginationTiebreakerSpec.scala

Fixes https://github.com/prisma/prisma/issues/3258

Fix pagination edge cases

---

server/servers/deploy/src/main/scala/com/prisma/deploy/schema/Errors.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/migration/inference/LegacyInfererIntegrationSpec.scala

* the validation catches a related error, I adjusted the message to not confuse users

Added test, adjusted error message

---

cli/packages/prisma-cli-engine/src/commands/help.ts

Partially fixes https://github.com/prisma/prisma/issues/4041

fix(cli-docs): replace GraphQL reference

---

server/build.sbt

Add execution rights for root group to `/app/bin/prisma-local` to fix the following error:
```bash
/app/start.sh: line 3: ./app/bin/prisma-local: Permission denied
```
The reason is that OpenShift is running the container with random UIDs they are stil in the root group. They are doing it to prevent to run the container with the root user for security reasons.
Fix #2945

Fix #2945 Cannot run on OpenShift

---

server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/database/MongoDeployDatabaseMutationBuilder.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/impl/MongoClientDbQueries.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/impl/mutactions/ColumnMutactionInterpreters.scala
server/connectors/deploy-connector/src/main/scala/com/prisma/deploy/connector/MigrationStepMapperImpl.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/AddingOptionalBackRelationDuringMigrationSpec.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/ChangingModelsOfRelationsSpec.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/IntegrationBaseSpec.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/RenamingWithExistingDataSpec.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/SeveralRelationsBetweenSameModelsIntegrationSpec.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/deploychecks/UpdateFieldDeploySpec.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/deploychecks/UpdateRelationDeploySpec.scala

Fixes https://github.com/prisma/prisma/issues/3855

Mongo Updating a Field to Unique Bug

---

server/servers/api/src/main/scala/com/prisma/api/mutactions/SubscriptionEvents.scala
server/servers/api/src/main/scala/com/prisma/util/coolArgs/GcConverters.scala

* correctly parse DateTime
* do not omit non-updated fields
Fixes https://github.com/prisma/prisma/issues/3603

Subscription DateTime Bug

---

server/.buildkite/docker-test-setups/docker-compose.test.postgres.yml
server/connectors/deploy-connector-jdbc/src/main/scala/com/prisma/deploy/connector/jdbc/database/JdbcDeployDatabaseMutationBuilder.scala
server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/database/MysqlJdbcDeployDatabaseMutationBuilder.scala
server/connectors/deploy-connector-postgres/src/main/scala/com/prisma/deploy/connector/postgres/database/PostgresJdbcDeployDatabaseMutationBuilder.scala
server/connectors/deploy-connector-sqlite/src/main/scala/com/prisma/deploy/connector/sqlite/database/SQLiteJdbcDeployDatabaseMutationBuilder.scala
server/project/Dependencies.scala

* remove duplicated code that was necessary due to this

Update jooq since a bug in rename was fixed

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/RelationActions.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/nonEmbedded/nestedMutations/NestedConnectMutationInsideUpdatev11Spec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/nonEmbedded/nestedMutations/SchemaBasev11.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/inference/SchemaInferrer.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/DataModelValidatorImpl.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/migration/DatabaseSchemaValidatorSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/migration/MigrationsSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/migration/inference/SchemaInfererEmbeddedSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/migration/inference/SchemaInferrerSpec.scala
server/servers/deploy/src/test/scala/com/prisma/shared/schema_dsl/SchemaDsl.scala
server/servers/deploy/src/test/scala/com/prisma/shared/schema_dsl/TestProject.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Schema.scala

Fixes https://github.com/prisma/prisma/issues/4106

Mongo connect not disconnecting old relation

---

server/libs/metrics/src/main/scala/com/prisma/metrics/micrometer/MicrometerMetricsRegistry.scala

Adds `PROMETHEUS_PUSHGATEWAY_ENDPOINT` env var.

Add env var for pushgateway endpoint

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/ImportActions.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/impl/ImportInterpreters.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/impl/JdbcDatabaseMutactionExecutor.scala
server/connectors/deploy-connector-jdbc/src/main/scala/com/prisma/deploy/connector/jdbc/database/JdbcDeployDatabaseMutationBuilder.scala
server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/MySqlDeployConnector.scala
server/connectors/deploy-connector-postgres/src/main/scala/com/prisma/deploy/connector/postgres/PostgresDeployConnector.scala
server/connectors/deploy-connector-sqlite/src/main/scala/com/prisma/deploy/connector/sqlite/SQLiteDeployConnector.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/schema/mutations/DeployMutation.scala

Fixes https://github.com/prisma/prisma/issues/4101

Do not create RelayId table or write to it when using datamodel v1.1

---

cli/packages/prisma-cli-engine/src/Client/Client.ts
cli/packages/prisma-yml/src/Cluster.ts
cli/packages/prisma-yml/src/utils/__snapshots__/parseEndpoint.test.ts.snap
cli/packages/prisma-yml/src/utils/parseEndpoint.test.ts
cli/packages/prisma-yml/src/utils/parseEndpoint.ts
cli/yarn.lock

fixes https://github.com/prisma/prisma/issues/4215

fix(token-provisioning): handle various cases of server and environment

---

cli/packages/prisma-cli-core/src/commands/account/account.ts
cli/packages/prisma-cli-core/src/commands/deploy/deploy.ts
cli/packages/prisma-cli-core/src/commands/generate/generate.ts

Fixes https://github.com/prisma/prisma/issues/3579
The warning comment has version `1.31`, since this is expected to hit stable at the 2nd release from today (current stable is `1.29`).

feat(generate): implicit generate after deploy

---

server/servers/api/src/main/scala/com/prisma/api/schema/InputTypesBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/schema/InputTypesSchemaBuilderSpec.scala

* do not render id as optional inputtype if it is not defined in the datamodel

Rendering of Id Input

---

cli/packages/prisma-cli-engine/src/Client/Client.ts
cli/packages/prisma-yml/src/Cluster.ts
cli/yarn.lock

Fixes https://github.com/prisma/prisma/issues/4215 wrt unsafe servers

fix(token): Do not generate token for unsafe servers

---

cli/packages/prisma-datamodel/__tests__/renderer/builtinDirectives.ts

Skip test made legacy by this: https://github.com/prisma/prisma/commit/3c4e34728c0130e7eb6baec9fc7fe2af81d67b0c

fix(tests): remove test for an unimplemented feature

---

cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts

Fixes https://github.com/prisma/prisma/issues/4282
Fixes https://github.com/prisma/prisma/issues/4052
Makes password field not visible while typing

fix(init-pg): init workflow pg

---

cli/packages/prisma-yml/src/Cluster.ts
cli/packages/prisma-yml/src/utils/__snapshots__/parseEndpoint.test.ts.snap
cli/packages/prisma-yml/src/utils/parseEndpoint.test.ts
cli/packages/prisma-yml/src/utils/parseEndpoint.ts

Fix "needsAuth"
Related: https://github.com/prisma/prisma/issues/4215

fix(token): treat internal api as private

---

cli/packages/prisma-cli-engine/src/Client/Client.ts
cli/packages/prisma-yml/src/Cluster.ts

Adds more debug statements for better dynamic debugging.
Further fixes https://github.com/prisma/prisma/issues/4215

fix(token): make needsAuth robust

---

cli/packages/prisma-cli-engine/src/Output/index.ts

Changed the forum link to spectrum in the error message

Change forum link to spectrum

---

cli/packages/prisma-cli-core/src/commands/deploy/deploy.ts

Implements
https://github.com/divyenduz/rfcs/blob/disable-hooks/text/0000-disable-hooks.md
Closes https://github.com/prisma/prisma/issues/2306
Does not implement the `--hook` part of spec as that is redundant
(subjected to further discussion)

feat(disable hooks): via a new flag

---

cli/packages/prisma-cli-engine/src/Client/Client.ts

Fixes https://github.com/prisma/prisma/issues/4322
Fixes https://github.com/prisma/prisma/issues/4312

fix(token): catch the addServiceToCloudDBIfMissing exception for debugging

---

cli/packages/prisma-cli-core/src/commands/deploy/deploy.ts
cli/packages/prisma-cli-core/src/commands/export/index.ts
cli/packages/prisma-cli-core/src/commands/import/index.ts
cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts
cli/packages/prisma-cli-core/src/utils/__snapshots__/EndpointDialog.test.ts.snap

Partial https://github.com/prisma/prisma/issues/4020

feat(cli-wording): adjust some wording

---

server/servers/subscriptions/src/main/scala/com/prisma/subscriptions/protocol/SubscriptionSessionActor.scala

[WIP] fix subscription termination

---

server/connectors/deploy-connector-postgres/src/main/scala/com/prisma/deploy/connector/postgres/database/PostgresJdbcDeployDatabaseMutationBuilder.scala
server/connectors/deploy-connector/src/main/scala/com/prisma/deploy/connector/MigrationValueGenerator.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/PrefillingFieldsWithDefaultOrMigrationValueSpec.scala

Fixes https://github.com/prisma/prisma/issues/4333

Migrationvalue for fields with ID type

---

cli/packages/prisma-cli-engine/src/Command.test.ts
cli/packages/prisma-cli-engine/src/Command.ts

Fixes indentation and adds alpha/beta support for https://github.com/divyenduz/rfcs/blob/cli-server-sync/text/0000-cli-server-sync.md

feat(warn): add support for alpha, beta

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/BuilderBase.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/ImportActions.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/RelationQueries.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/ResultSetReaders.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/DataResolverTypes.scala
server/servers/api/src/main/scala/com/prisma/api/import_export/BulkExport.scala

* enables the handling of inline relations

Import export adjustments for new datamodel

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/ImportActions.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/RelationQueries.scala
server/servers/api/src/test/scala/com/prisma/api/import_export/InlineRelationImportExportSpec.scala

Import Export Tests

---

cli/packages/prisma-cli-core/src/commands/delete/index.ts

Fixes https://github.com/prisma/prisma/issues/4306

fix(delete): message

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/AggregationQueryBuilder.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeManyQueries.scala
server/servers/api/src/test/scala/com/prisma/api/queries/MultiItemConnectionQuerySpec.scala
server/servers/api/src/test/scala/com/prisma/api/queries/RelationFilterOrderingSpec.scala

Fixes https://github.com/prisma/prisma/issues/4290
Fixes https://github.com/prisma/prisma/issues/4414
Fixes https://github.com/prisma/prisma/issues/4427

Mongo Aggregation Fixes

---

docs/1.32/get-started/03-build-rest-apis-with-prisma-TYPESCRIPT-t202.mdx

curl request was wrong, now right

Update put curl request

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/BuilderBase.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/FilterConditionBuilder.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/ImportActions.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/NodeSingleQueries.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/RelationActions.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/ValidationActions.scala
server/prisma-rs/prisma-models/src/field/relation.rs
server/prisma-rs/prisma-models/src/relation.rs
server/servers/api/src/test/scala/com/prisma/api/filters/nonEmbedded/SelfRelationFilterBugSpec.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Field.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Relation.scala

Fixes https://github.com/prisma/prisma/issues/4508
Fixes https://github.com/prisma/prisma/issues/4452

Self Relation Bug with Inline Ids

---

server/connectors/api-connector/src/main/scala/com/prisma/api/schema/Errors.scala
server/servers/api/src/main/scala/com/prisma/util/coolArgs/CoolArgs.scala
server/servers/api/src/test/scala/com/prisma/api/filters/nonEmbedded/WhereUniqueSpec.scala

* add centralized test for expected WhereUnique shape and behavior
* also error when more than one field is provided
Fixes https://github.com/prisma/prisma/issues/4509

Invalid WhereUnique Bug

---

docs/1.29/prisma-cli-and-configuration/prisma-yml-5cy7.mdx

graphql-schema generator outputs a single file

---

docs/1.33/prisma-cli-and-configuration/prisma-yml-5cy7.mdx

graphql-schema now outputs to a single file instead of a directory

Fix graphql-schema documentation

---

server/libs/sangria-server/src/main/resources/admin.html

0.3.x adds support for embedded types

Bump admin version to 0.3.x

---

server/prisma-rs/libs/datamodel/src/ast/parser/datamodel.pest
server/prisma-rs/libs/datamodel/src/ast/parser/mod.rs
server/prisma-rs/libs/datamodel/src/common/functions/builtin.rs
server/prisma-rs/libs/datamodel/src/common/functions/mod.rs
server/prisma-rs/libs/datamodel/src/dml/field.rs
server/prisma-rs/libs/datamodel/src/dml/validator/common.rs
server/prisma-rs/libs/datamodel/src/dml/validator/directive/core/mod.rs
server/prisma-rs/libs/datamodel/src/dml/validator/directive/core/updated_at.rs
server/prisma-rs/libs/datamodel/src/dml/validator/lift.rs
server/prisma-rs/libs/datamodel/src/dml/validator/standardise.rs
server/prisma-rs/libs/datamodel/src/dmmf/dmmf.rs
server/prisma-rs/libs/datamodel/src/dmmf/from_dmmf.rs
server/prisma-rs/libs/datamodel/src/dmmf/to_dmmf.rs
server/prisma-rs/libs/datamodel/tests/base/basic.rs
server/prisma-rs/libs/datamodel/tests/common.rs
server/prisma-rs/libs/datamodel/tests/directives/mod.rs
server/prisma-rs/libs/datamodel/tests/directives/relations_consistency.rs
server/prisma-rs/libs/datamodel/tests/directives/relations_legacy.rs
server/prisma-rs/libs/datamodel/tests/directives/relations_negative.rs
server/prisma-rs/libs/datamodel/tests/directives/updated_at_negative.rs
server/prisma-rs/libs/datamodel/tests/directives/updated_at_positive.rs
server/prisma-rs/libs/datamodel/tests/end_to_end/parser_renderer_dml.rs
server/prisma-rs/libs/datamodel/tests/end_to_end/parser_renderer_dmmf.rs
server/prisma-rs/libs/datamodel/tests/functions/server_side_functions.rs
server/prisma-rs/libs/datamodel/tests/parsing/nice_errors.rs
server/prisma-rs/libs/datamodel/tests/renderer/simplification.rs
server/prisma-rs/libs/datamodel/tests/types/negative.rs
server/prisma-rs/libs/datamodel/tests/types/positive.rs

Please see commits for inidividual changes.

Parser Adjustments

---

cli/packages/prisma-cli-engine/src/Config.ts
cli/packages/prisma-db-introspection/package.json
cli/packages/prisma-db-introspection/src/cli/index.ts
cli/packages/prisma-db-introspection/src/cli/introspect/util.ts
cli/packages/prisma-db-introspection/src/cli/prisma-config/PrismaDefinition.ts
cli/packages/prisma-db-introspection/src/cli/prisma-config/yaml.ts
cli/packages/prisma-db-introspection/src/cli/prompt-lib/BoxPrompt.tsx
cli/packages/prisma-db-introspection/src/cli/prompt-lib/Checkbox.tsx
cli/packages/prisma-db-introspection/src/cli/prompt-lib/Divider.tsx
cli/packages/prisma-db-introspection/src/cli/prompt-lib/SelectItem.tsx
cli/packages/prisma-db-introspection/src/cli/prompt-lib/Spinner.tsx
cli/packages/prisma-db-introspection/src/cli/prompt-lib/TextInput.tsx
cli/packages/prisma-db-introspection/src/cli/prompt-lib/helpers.ts
cli/packages/prisma-db-introspection/src/cli/prompt-lib/types.ts
cli/packages/prisma-db-introspection/src/cli/prompt-lib/useStdin.ts
cli/packages/prisma-db-introspection/src/cli/prompts/CredentialPrompt.tsx
cli/packages/prisma-db-introspection/src/cli/prompts/prompts-elements.ts
cli/packages/prisma-db-introspection/src/cli/types.ts
cli/packages/prisma-db-introspection/src/common/normalization/modelNameNormalizer.ts
cli/packages/prisma-db-introspection/src/databases/relational/relationalConnector.ts
cli/packages/prisma-db-introspection/src/index.ts
cli/packages/prisma-db-introspection/tsconfig.json
cli/yarn.lock

One concern:
That PR adds a *lot* of dependencies because of the CLI. It might be wise to keep the cli separated from the actual runtime introspection code

Add prisma introspect command

---

cli/prisma2/introspection/src/commands/Init.ts
cli/prisma2/introspection/src/prompt/steps/3-select-database-schema.tsx
cli/prisma2/introspection/src/types.ts

When in introspection mode (not sqlite3), print the introspected sdl.

fix init introspection

---

cli/prisma2/introspection/src/introspect/util.ts
cli/prisma2/introspection/src/prompt/prompts-elements.ts
cli/prisma2/introspection/src/prompt/steps/2-input-credentials.tsx

- add margin for mysql
- fallback to default when credentials are empty strings

allow introspection of databases with 0 tables.

---

server/prisma-rs/current_connector
server/prisma-rs/libs/datamodel/src/common/functions/builtin.rs
server/prisma-rs/libs/datamodel/src/configuration/source/builtin/postgres_source.rs
server/prisma-rs/libs/datamodel/src/configuration/source/loader.rs
server/prisma-rs/libs/datamodel/src/errors/errors.rs
server/prisma-rs/libs/datamodel/src/lib.rs
server/prisma-rs/libs/datamodel/tests/config/builtin.rs
server/prisma-rs/libs/datamodel/tests/end_to_end/parser_renderer_dmmf.rs
server/prisma-rs/libs/datamodel/tests/functions/string_interpolation.rs
server/prisma-rs/migration-engine/connectors/sql-migration-connector/src/lib.rs
server/prisma-rs/migration-engine/core/src/connector_loader.rs
server/prisma-rs/migration-engine/core/tests/test_harness/misc_helpers.rs
server/prisma-rs/prisma-fmt/src/main.rs

Tackles https://github.com/prisma/prisma2/issues/1.

Better Linting, rename postgres

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeActions.scala

Fixes https://github.com/prisma/prisma/issues/4716

Do not store ids under id and _id when they are user provided

---

server/prisma-rs/libs/datamodel/tests/directives/relations_positive.rs
server/prisma-rs/migration-engine/connectors/sql-migration-connector/src/database_inspector/mysql_inspector.rs
server/prisma-rs/migration-engine/connectors/sql-migration-connector/src/database_inspector/postgres_inspector.rs
server/prisma-rs/migration-engine/connectors/sql-migration-connector/src/database_inspector/sqlite_inspector.rs
server/prisma-rs/migration-engine/connectors/sql-migration-connector/src/lib.rs
server/prisma-rs/migration-engine/core/src/commands/migration_progress.rs
server/prisma-rs/migration-engine/core/tests/migrations_tests.rs
server/prisma-rs/migration-engine/core/tests/test_harness/misc_helpers.rs
server/prisma-rs/prisma-models/src/datamodel_converter.rs
server/prisma-rs/prisma-models/tests/datamodel_converter_tests.rs

fixes:
https://github.com/prisma/prisma2/issues/14
https://github.com/prisma/lift/issues/21
https://github.com/prisma/prisma2/issues/42
https://github.com/prisma/lift/issues/17
https://github.com/prisma/lift/issues/13

fixes for migration-engine for next preview release

---

server/connectors/deploy-connector-postgres/src/main/scala/com/prisma/deploy/connector/postgres/database/PostgresJdbcDeployDatabaseMutationBuilder.scala
server/connectors/deploy-connector-sqlite/src/main/scala/com/prisma/deploy/connector/sqlite/database/SQLiteJdbcDeployDatabaseMutationBuilder.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/DeployingCustomIdNamesSpec.scala

use the correct column reference in relationtable create statements for Postgres and SQLite
Fixes https://github.com/prisma/prisma/issues/4569

Fix Relationtable bug in Postgres and SQLite

---

server/prisma-rs/libs/datamodel/src/dml/validator/standardise.rs
server/prisma-rs/libs/datamodel/tests/directives/relations_consistency.rs

fixes: https://github.com/prisma/prisma2/issues/82

fix issue 82

---

server/connectors/deploy-connector-jdbc/src/main/scala/com/prisma/deploy/connector/jdbc/DatabaseInspectorBase.scala
server/connectors/deploy-connector-jdbc/src/main/scala/com/prisma/deploy/connector/jdbc/PostgresDatabaseInspector.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/migration/ExistingDatabasesSpec.scala

Fixes https://github.com/prisma/prisma/issues/4190

Introspection should not fail on types Prisma can't handle at the moment

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/CustomUpdateCombiner.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeActions.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/DeleteManyBugSpec.scala

Fixes https://github.com/prisma/prisma/issues/4767

Mongo Delete Many Bug

---

server/prisma-rs/Cargo.lock
server/prisma-rs/libs/database-introspection/src/lib.rs
server/prisma-rs/libs/database-introspection/src/postgres.rs
server/prisma-rs/libs/database-introspection/src/sqlite.rs
server/prisma-rs/libs/database-introspection/tests/introspection_connection_tests.rs
server/prisma-rs/prisma-models/src/prisma_value.rs

Handle `ON DELETE` actions for foreign keys in Postgres.

Database-introspection: Handle ON DELETE actions for foreign keys

---

server/prisma-rs/Cargo.lock
server/prisma-rs/libs/database-introspection/Cargo.toml
server/prisma-rs/libs/database-introspection/src/sqlite.rs
server/prisma-rs/libs/database-introspection/tests/introspection_connection_tests.rs

Fix index detection in SQLite introspection.

Fix SQLite introspection

---

server/prisma-rs/Cargo.lock

Fix the barrel revision depended on, as I wiped the previous one by force pushing (sorry!).

Fix barrel version

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/FilterConditionBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/filters/nonEmbedded/RelationIsNullSpec.scala
server/shared-models/src/main/scala/com/prisma/shared/models/ConnectorCapabilities.scala

Fixes https://github.com/prisma/prisma/issues/4784

One relation is null bug

---

server/prisma-rs/libs/database-introspection/Cargo.toml
server/prisma-rs/libs/database-introspection/src/lib.rs
server/prisma-rs/libs/database-introspection/src/mysql.rs
server/prisma-rs/libs/database-introspection/src/postgres.rs
server/prisma-rs/libs/database-introspection/src/sqlite.rs
server/prisma-rs/libs/database-introspection/tests/introspection_connection_tests.rs
server/prisma-rs/libs/database-introspection/tests/resources/schema-all-column-arities.json
server/prisma-rs/libs/database-introspection/tests/resources/schema-all-column-type-families.json
server/prisma-rs/libs/database-introspection/tests/resources/schema-all-foreign-key-actions.json
server/prisma-rs/libs/database-introspection/tests/resources/schema-without-primary-key.json
server/prisma-rs/libs/database-introspection/tests/resources/schema.json
server/prisma-rs/libs/database-introspection/tests/serialization_tests.rs

Make the schema returned by Rust-based introspection serializable.

Make introspection schema serializable

---

server/prisma-rs/libs/database-introspection/src/lib.rs
server/prisma-rs/libs/database-introspection/tests/serialization_tests.rs

Fix result type definition in database-introspection.

Fix result type definition in database-introspection

---

server/prisma-rs/libs/database-introspection/tests/introspection_connection_tests.rs

Clean up Rust introspection tests

---

server/prisma-rs/libs/database-introspection/src/mysql.rs
server/prisma-rs/libs/database-introspection/src/sqlite.rs
server/prisma-rs/libs/database-introspection/tests/introspection_connection_tests.rs

Fix detection of foreign key actions for MySQL and SQLite.

Fix foreign key actions for MySQL and SQLite

---

server/prisma-rs/libs/database-introspection/src/mysql.rs
server/prisma-rs/libs/database-introspection/src/sqlite.rs
server/prisma-rs/libs/database-introspection/tests/introspection_connection_tests.rs

Run cargo fmt on database-introspection.

database-introspection: Formatting

---

server/prisma-rs/libs/database-introspection/src/lib.rs
server/prisma-rs/libs/database-introspection/src/mysql.rs
server/prisma-rs/libs/database-introspection/src/postgres.rs
server/prisma-rs/libs/database-introspection/src/sqlite.rs
server/prisma-rs/libs/database-introspection/tests/introspection_connection_tests.rs

Document database introspection and remove dead code.

Cleanup introspection

---

server/prisma-rs/Cargo.lock
server/prisma-rs/Cargo.toml
server/prisma-rs/libs/database-introspection/src/lib.rs
server/prisma-rs/libs/database-introspection/tests/introspection_connection_tests.rs
server/prisma-rs/libs/database-introspection/tests/serialization_tests.rs
server/prisma-rs/libs/introspection-command/Cargo.toml
server/prisma-rs/libs/introspection-command/README.md
server/prisma-rs/libs/introspection-command/src/lib.rs
server/prisma-rs/libs/introspection-command/tests/introspection_command_tests.rs
server/prisma-rs/libs/logger/src/lib.rs

Implement the generating of data models from introspection results in Rust.

Implement generating of data models in Rust

---

server/prisma-rs/libs/database-introspection/src/lib.rs
server/prisma-rs/libs/introspection-command/src/lib.rs
server/prisma-rs/libs/introspection-command/tests/introspection_command_tests.rs

Add introspection-command test for field arity. Please merge #4832 first.

introspection-command: Add test for arity

---

cli/packages/prisma-cli-engine/src/Output/index.ts

Change CLI output from spectrum to slack

---

cli/packages/prisma-cli-core/package.json
cli/yarn.lock

This fixes the current build cli error: https://app.circleci.com/jobs/github/prisma/prisma/6662

chore(cli-core): update prisma-db-introspection package

---

docs/1.34/datamodel-and-migrations/datamodel-MYSQL-knul.mdx

A very minor grammar fix for the documentation.

Small grammar fix

---

docs/1.34/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4.mdx

Some more minor grammar fixes for the docs.

Small grammar fixes

---

README.md

This PR tries to fix all the links in the README.
Still could use some updates to Prisma 2 wording though.

fix(README): fix all the links

---

docs/1.34/get-started/01-setting-up-prisma-demo-server-TYPESCRIPT-t001.mdx

fix typo in 01-setting-up-prisma-demo-server-TYPESCRIPT-t001.mdx

---

docs/1.34/datamodel-and-migrations/introspection-MYSQL-soi2.mdx

The introspection documentation for MySQL referred to querying a Postgres database.

Correct wording incorrectly referring to Postgres

---

docs/1.34/datamodel-and-migrations/datamodel-MYSQL-knul.mdx
docs/1.34/datamodel-and-migrations/datamodel-POSTGRES-knum.mdx

Noticed when reading through them, pretty sure this is what was intended.

Fixed a missing word in the docs.

---

docs/1.34/faq/why-does-prisma-need-a-server-fq02.mdx

I think this is what you guys meant to put there!

small grammar error

---

docs/1.34/prisma-client/basic-data-access/reading-data-GO-go05.mdx
docs/1.34/prisma-client/basic-data-access/reading-data-JAVASCRIPT-rsc2.mdx
docs/1.34/prisma-client/basic-data-access/reading-data-TYPESCRIPT-rsc3.mdx

syntax error corrected

---

docs/1.28/datamodel-and-migrations/datamodel-MYSQL-knul.mdx

Fix spelling in datamodel-MYSQL

---

cli/packages/prisma-datamodel/__tests__/clone/clone.ts

Fix spelling error in test
