docs/04-Reference/02-Graphcool-CLI/02-Commands.md

The location of the `email-password` template is `auth/`, not `messaging/`.

Fix command to pull in the email-password template

---

docs/01-Quickstart/01-Frontend/01-React/01-Apollo.md
docs/01-Quickstart/01-Frontend/01-React/02-Relay.md
docs/01-Quickstart/01-Frontend/02-React-Native/01-Apollo.md
docs/01-Quickstart/01-Frontend/03-Vue/01-Apollo.md
docs/01-Quickstart/01-Frontend/04-Angular/01-Apollo.md
docs/01-Quickstart/01-Frontend/05-iOS/01-Apollo.md
docs/03-Tutorials/02-Auth/02-Authentication-with-Email-and-Password-for-React-&-Apollo.md

Some type declaration on docs were not using the new syntax, thus when following the tutorial, the user would get the following error when trying to deploy:
```
Creating service server in cluster shared-eu-west-1... ✔
Bundling functions... 2.3s
Deploying... 384ms
There are issues with the new service definition:
Post
✖ The model `Post` is missing the @model directive. Please add it. See: https://github.com/graphcool/graphcool/issues/817
```

Fixed type declaration syntax on docs (missing @model)

---

docs/01-Quickstart/02-Backend/01-TypeScript/01-TypeScript.md
examples/typescript-gateway-custom-schema/README.md

given the latest sample code, the final query in this quickstart guide was generating the following error:
`Unknown argument "limit" on field "posts" of type "User"`
this could be fixed by removing the limit, or by requesting topPosts one level up on the viewer model. i went with the latter option as it also demonstrates the limit, rather than simply returning all posts. also corrected a very minor typo in a sentence above this.

using topPosts in final query to prevent error

---

examples/permissions/graphcool.yml

Especially the fact that specifying fields on a permission means that the permission applies *only* to those fields.

Improve permission explanations

---

server/backend-shared/src/main/scala/cool/graph/client/MutationQueryWhitelist.scala
server/client-shared/src/main/scala/cool/graph/client/schema/SchemaBuilder.scala
server/client-shared/src/test/scala/cool/graph/private_api/finder/CachedProjectFetcherImplSpec.scala

* currently making use of an alias in a mutation results in a permission error if no read permissions for created fields are set
* but creating a field should always whitelist that path for the permission check

Add Aliases to Permission Whitelist

---

server/backend-api-system/src/main/scala/cool/graph/system/externalServices/AlgoliaKeyChecker.scala
server/backend-workers/src/main/scala/cool/graph/worker/workers/WebhookDelivererWorker.scala
server/client-shared/src/main/scala/cool/graph/client/requestPipeline/FunctionExecutor.scala
server/libs/akka-utils/src/main/scala/cool/graph/akkautil/http/SimpleHttpClient.scala
server/libs/akka-utils/src/test/scala/cool/graph/akkautil/http/SimpleHttpClientSpec.scala

- Minor semantic change to SimpleHttpClient: Distinguish certain failure conditions (status code, request unmarshalling) directly in the error classes.
- Replace an akka HTTP implemenation in FunctionExecutor (that I missed earlier) with SimpleHttpClient.

SimpleHttpClient cleanup

---

server/backend-api-system/src/main/scala/cool/graph/system/migration/ProjectConfig.scala

In addition to 
```yaml
types: ./types.graphql
functions:
WebhookFunction:
isEnabled: true
handler:
webhook:
url: http://some.url
type: operationBefore
operation: "TestModel.create"
permissions: []
rootTokens: []
``` 
this is now also enabled
```yaml
types: ./types.graphql
functions:
WebhookFunction:
isEnabled: true
handler:
webhook: http://some.url
type: operationBefore
operation: "TestModel.create"
permissions: []
rootTokens: []
```

Allow shortcut for webhook url definition if no headers are present

---

server/backend-api-system/src/main/scala/cool/graph/system/migration/permissions/PermissionsDiff.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutations/DeleteFieldMutation.scala

* fix for https://github.com/graphcool/framework/issues/993
* make sure the updatedProject after a deleteFieldMutation is not referencing the deleted field in the model permissions anymore
* this will prevent us from erroring early with the 'Field with id not found'  and output the correct error later on that contains the Model and field that does not exist

Fix Field With Id Not Found

---

server/client-shared/src/main/scala/cool/graph/client/requestPipeline/FunctionExecutor.scala
server/libs/akka-utils/src/main/scala/cool/graph/akkautil/http/SimpleHttpClient.scala

Prevent Akka HTTP double unmarshal (which results in a streaming error).

Fix HTTP resolvers

---

server/libs/akka-utils/src/main/scala/cool/graph/akkautil/http/SimpleHttpClient.scala
server/libs/akka-utils/src/test/scala/cool/graph/akkautil/http/SimpleHttpClientSpec.scala

Sometimes the request pipeline returns 5003 (BadBody) instead of 5000 (BadStatusCode) if the function returned a non-2xx status code.
Findings: Akka Http treated redirects as success in the .isSuccess call. Changing the behaviour to check between 200 (inclusive) and 300 (exclusive) apparently fixes the issue.

Fix flaky request pipeline behaviour

---

docs/04-Reference/05-Functions/05-Resolvers.md

`subscription` -> `resolver`
`CELCIUS` -> `CELSIUS` (https://en.wikipedia.org/wiki/Celcius_(disambiguation))
Updated text that had been copied from the `Subscriptions` document that does not apply here

Fix typos in resolvers documentation

---

server/backend-api-system/src/main/scala/cool/graph/system/mutactions/client/CreateColumn.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutactions/client/CreateModelTable.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutactions/internal/CreateModel.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutactions/internal/CreateModelWithoutSystemFields.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutactions/internal/CreateRelation.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutactions/internal/UpdateField.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutactions/internal/UpdateModel.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutactions/internal/UpdateRelation.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutactions/internal/validations/EnumValueValidation.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutactions/internal/validations/ProjectValidations.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutactions/internal/validations/TypeNameValidation.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutations/PushMutation.scala
server/backend-shared/src/main/scala/cool/graph/shared/errors/Errors.scala

Fix for https://github.com/graphcool/framework/issues/994
The invalid name error was very generic and did not mention the type. It will now specify whether it was a model, field, relation or enum that had a naming convention violation.
Since several mutactions can throw the same naming violation error in one deploy we now also filter the error messages for duplicates.

Add type to invalid name error message.

---

cli/packages/graphcool-cli-core/src/commands/deploy/Bundler/proxies/dev.js

In local execution, the function called needed to return something. If the function didn't return anything we had a `Cannot read property 'then' of undefined`.
Like that now we can handle properly the functions that return nothing (really useful in subscription functions for exemple)

allow function to return anything, even nothing in local mode

---

cli/packages/graphcool-cli-core/src/commands/deploy/Bundler/Bundler.ts

This patch fixes the deployment to shared clusters from Windows. :tada:
Fixes #1031, fixes #836, fixes #885.

Fix Windows deployment paths

---

cli/packages/graphcool-cli-core/src/commands/info/index.ts
cli/packages/graphcool-cli-core/src/commands/logs/function.ts
cli/packages/graphcool-cli-core/src/commands/root-token/index.ts

Fixes #1067.
Applies to `gc logs`, `gc info` and `gc root-token`.

No online authorization required for local cluster commands

---

docs/04-Reference/06-Auth/02-Authentication/02-Authentication-Tokens.md

If I understand it correctly, [is `generateAuthToken` deprecated](https://github.com/graphcool/framework/issues/874).
(There is also an open [PR in the graphcool-lib](https://github.com/graphcool/graphcool-lib/pull/15) repo that fixes the example in the graphcool-lib README)

Fix docs: rename generateAuthToken to generateNodeToken

---

docs/04-Reference/06-Auth/02-Authentication/02-Authentication-Tokens.md

This flag doesn't appear to exist anymore

docs/auth: Remove --token flag

---

server/backend-api-system/src/main/scala/cool/graph/system/mutactions/client/DeleteAllRelayIds.scala
server/backend-api-system/src/main/scala/cool/graph/system/mutations/ResetProjectDataMutation.scala
server/backend-shared/src/main/scala/cool/graph/client/database/ProjectDataresolver.scala

Otherwise there will be foreign key constraint problems when wiped model ids are entered again.

The ResetProjectDataMutation should wipe the RelayIds as well

---

cli/packages/graphcool-cli-core/src/commands/invoke/local.ts

when invoking a local function the CLI suggests an incorrect command: "invoke local", instead of "invoke-local"

fixed print-out typo

---

cli/packages/graphcool-cli-engine/src/Environment.ts

Fixes #1451
The `lstat` throws an exception when trying to access no existing file/directory. Another way would be `try/catch` block, but since there is already check for `exists` then this is enough.

Handle for a missing .graphcool directory

---

server/deploy/src/main/scala/cool/graph/deploy/database/persistence/DbToModelMapper.scala
server/deploy/src/main/scala/cool/graph/deploy/database/persistence/MigrationPersistence.scala
server/deploy/src/main/scala/cool/graph/deploy/database/persistence/MigrationPersistenceImpl.scala
server/deploy/src/main/scala/cool/graph/deploy/database/persistence/ModelToDbMapper.scala
server/deploy/src/main/scala/cool/graph/deploy/database/schema/InternalDatabaseSchema.scala
server/deploy/src/main/scala/cool/graph/deploy/database/tables/Migration.scala
server/deploy/src/main/scala/cool/graph/deploy/migration/migrator/MigrationApplier.scala
server/deploy/src/main/scala/cool/graph/deploy/schema/CustomScalarTypes.scala
server/deploy/src/main/scala/cool/graph/deploy/schema/types/MigrationType.scala
server/deploy/src/test/scala/cool/graph/deploy/database/persistence/MigrationPersistenceImplSpec.scala
server/deploy/src/test/scala/cool/graph/deploy/migration/migrator/MigrationApplierSpec.scala
server/shared-models/src/main/scala/cool/graph/shared/models/Migration.scala

Rudimentary tracking of start and finish times for database migrations.

[1.0] Migration timestamps

---

examples/1.0/auth/database/graphcool.yml
examples/1.0/file-api/database/graphcool.yml
examples/1.0/github-auth/graphcool.yml
examples/1.0/permissions/README.md
examples/1.0/permissions/database/graphcool.yml
examples/1.0/rest-wrapper/database/graphcool.yml
examples/1.0/subscriptions/database/graphcool.yml

- Remove local cluster option from 1.0 examples, to allow choosing a cluster on deployment.
- update download link in permissions example

Removing local cluster from graphcool.yml

---

docs/1.0/06-GraphQL-Ecosystem/01-GraphQL-Yoga/01-Overview.md

I found a few links that were out of date and updated them to go to the new locations.

Update links to graphql-yoga examples

---

README.md

This PR:
- Removes `rest-wrapper`, which is no longer in the examples directory
- Corrects `file-api` to `file-handling-s3`

Updates Examples in README

---

server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/NestedRelationMutactionBaseClass.scala
server/api/src/test/scala/com/prisma/api/mutations/NestedConnectMutationInsideCreateSpec.scala

We were assuming that a relation always has two relationfields, but recently switched to optional backrelations, which is why this check was causing errors. We will now assume for the checks that the side without a relationfield is a list and is not required. Fixes https://github.com/graphcool/prisma/issues/1754

Relations that did not have two relation fields cause error in relation checks

---

docs/1.1/04-Reference/02-Prisma-API/02-Concepts.md

This is just a documentation fix. The headline says `Retrieve a single node by its email`, but the example passes an `id` as the argument.

docs: fix wrong query argument

---

server/api/src/main/scala/com/prisma/api/database/DatabaseMutationBuilder.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/NestedRelationMutactionBaseClass.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/UpsertDataItem.scala
server/api/src/main/scala/com/prisma/api/database/mutactions/mutactions/UpsertDataItemIfInRelationWith.scala
server/api/src/main/scala/com/prisma/api/mutations/SqlMutactions.scala
server/api/src/main/scala/com/prisma/api/schema/InputTypesBuilder.scala
server/api/src/test/scala/com/prisma/api/mutations/NestedUpsertMutationInsideUpdateSpec.scala
server/api/src/test/scala/com/prisma/api/mutations/OptionalBackrelationSpec.scala
server/api/src/test/scala/com/prisma/api/schema/MutationsSchemaBuilderSpec.scala

Fix for https://github.com/graphcool/prisma/issues/1837
- generate the update and upsert input types when there is no backrelation
- adds relation handling for the create case of upsert
- also adds the relay id table entries in the create case of upsert
- add relation test cases for nested upsert in update

Update and Upsert missing in nested API

---

server/api/src/main/scala/com/prisma/api/schema/InputTypesBuilder.scala
server/api/src/test/scala/com/prisma/api/mutations/NestedUpdateMutationInsideUpdateSpec.scala
server/api/src/test/scala/com/prisma/api/mutations/UpdateMutationSpec.scala
server/api/src/test/scala/com/prisma/api/schema/MutationsSchemaBuilderSpec.scala

- rename the InputTypes for models with optional backrelations so that they are unique
- verify schema generation for optional back relations
Fixes https://github.com/graphcool/prisma/issues/1909

UpdateMutation regression

---

cli/packages/prisma-yml/src/Cluster.ts

This PR proposes to sanitize the `baseUrl` by removing a possible trailing slash.
Reference: https://github.com/graphcool/prisma/issues/1955

fix: remove trailing slash from configured `baseUrl`

---

cli/CONTRIBUTING.md

Small update to `cli/CONTRIBUTING.md` to add a step for installing `prisma-yml` dependencies.
Closes #1932

fix cli contributing docs

---

docs/1.2/03-Tutorials/02-GraphQL-Server-Development/01-Deployment-with-Now.md

The `now --dotenv` flag by default uses the file `.env`, so I removed the explicit mentioning of this file.
The example regarding "production" was pointing to the wrong `.env` instead of `.env.prod`.

chore(docs): clarify usage of .env and now

---

server/api/src/main/scala/com/prisma/api/schema/Errors.scala
server/api/src/main/scala/com/prisma/api/server/ApiServer.scala
server/api/src/main/scala/com/prisma/api/server/RequestHandler.scala
server/api/src/test/scala/com/prisma/api/server/RequestHandlerSpec.scala
server/libs/sangria-utils/src/main/scala/com/prisma/sangria/utils/ErrorHandler.scala

always return  a valid GraphQL error of the shape: '"errors": ["message": "...", "requestId": "..."]'

Standardize the error format to be valid GraphQL

---

server/images/prisma-prod/src/main/scala/com/prisma/prod/PrismaProdMain.scala
server/libs/akka-utils/src/main/scala/com/prisma/akkautil/http/SimpleHttpClient.scala
server/libs/metrics/src/main/scala/com/prisma/metrics/MetricsManager.scala
server/libs/metrics/src/main/scala/com/prisma/metrics/StatsdHealthChecker.scala
server/libs/metrics/src/main/scala/com/prisma/metrics/StatsdHostLookup.scala

- Allows the metrics implementation to periodically check the health of the picked statsd buddy instance.
- Automatically fails over to another available statsd instance in case a health check fails.

Metrics health check and recovery

---

server/libs/akka-utils/src/main/scala/com/prisma/akkautil/throttler/Throttler.scala
server/servers/api/src/main/scala/com/prisma/api/server/ApiServer.scala

This additionally fixes throttling rates not being applied correctly, currently the case for prisma demo clusters.

Update throttling to akka 2.5.x streams

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/DatabaseMutationBuilder.scala
server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/database/DatabaseQueryBuilder.scala
server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/impl/DatabaseMutactionExecutorImpl.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/DeadlockSpec.scala

Prisma has tight control over data access patterns and can use this to provide sufficient guarantees without the prohibitively expensive Repeatable Reads isolation level that is the default in MySQL. Most other SQL databases (Oracle, SQL Server, PostgreSQL) default to Read Committed.
fixes #2060

Change isolation level to Read Committed

---

server/images/prisma-local/src/main/scala/com/prisma/local/PrismaLocalDependencies.scala
server/images/prisma-prod/src/main/scala/com/prisma/prod/PrismaProdDependencies.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/DeployDependencies.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/auth/AsymmetricClusterAuth.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/auth/ClusterAuth.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/auth/DummyClusterAuth.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/auth/SymmetricClusterAuth.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/server/auth/AsymmetricClusterAuthSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/server/auth/SymmetricClusterAuthSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/specutils/DeployTestDependencies.scala

Adds support for HS256 JWT authentication to the cluster API.
The decision which auth module is loaded is made during server bootup: 
* If the env var `PRISMA_MANAGEMENT_API_JWT_SECRET` is present and non-empty, it will load the HS256 JWT auth module.
* If the above env var is not present or empty, and the env var `CLUSTER_PUBLIC_KEY` (the "old" env var for cluster API auth) is present, it will load the RS256 JWT auth module.
* If both env vars are present and non-empty, the HS256 module is loaded.
* If both env vars are not present or empty, no auth module will be loaded and the cluster API is unsecured.

Support HMAC JWT auth for cluster API

---

server/servers/api/src/main/scala/com/prisma/api/server/ApiServer.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/schema/Errors.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/schema/mutations/AddProjectMutation.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/database/schema/mutations/AddProjectMutationSpec.scala
server/servers/subscriptions/src/main/scala/com/prisma/websocket/WebsocketServer.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Ids.scala
server/shared-models/src/test/scala/com/prisma/shared/models/ProjectIdSpec.scala

Adds support for default service names and stages:
* Makes it possible to deploy and query a service without name and stage, which will then deploy to the default service and default stage of the Prisma instance, routed under root `<prisma_url>/` (or explicitly at `<prisma_url>/default/default`).
* Makes it possible to deploy and query a service without a stage, which defaults to the `default` stage internally. The service is routed as `<prisma_url>/<service_name>` (or explicitly at `<prisma_url>/<service_name>/default`)
Export and import endpoints are still available on the simplified routes, e.g. `/export` is the endpoints for the `default/default` service, `/testService/export` the endpoint for the `testService/default` service.
To avoid ambiguities, this PR also introduces reserved …

Support for default service name and stage

---

docs/1.7/03-Tutorials/04-Cluster-Deployment/01-Digital-Ocean-(Docker-Machine).md

On [step 6](https://www.prisma.io/docs/tutorials/cluster-deployment/digital-ocean-(docker-machine)-texoo9aemu), in what shell are we running mkdir? I'm showing docker-machine active to be prisma but running `mkdir` is doing it on my local machine. I created all the files by ssh'ing into the droplet, but i'm feeling like i'm missing something about running these commands inside the docker container. If I run `docker-compose up -d` from inside the container, it says docker-compose is not installed.

rookie friendly edit

---

server/.buildkite/pipeline.sh
server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/database/MysqlDeployDatabaseQueryBuilder.scala
server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/impls/MysqlClientDbQueries.scala
server/connectors/deploy-connector-postgresql/src/main/scala/com/prisma/deploy/connector/postgresql/PostgresDeployConnector.scala
server/connectors/deploy-connector-postgresql/src/main/scala/com/prisma/deploy/connector/postgresql/database/PostgresDeployDatabaseQueryBuilder.scala
server/connectors/deploy-connector-postgresql/src/main/scala/com/prisma/deploy/connector/postgresql/impls/PostgresClientDbQueries.scala
server/connectors/deploy-connector-postgresql/src/main/scala/com/prisma/deploy/connector/postgresql/impls/PostgresDeployMutactionExecutor.scala
server/connectors/deploy-connector/src/main/scala/com/prisma/deploy/connector/DeployConnector.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/AddingOptionalBackRelationDuringMigrationSpec.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/ChangingFromRelationToScalarOrBackSpec.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/SeveralRelationsBetweenSameModelsIntegrationSpec.scala
server/libs/json-utils/src/main/scala/com/prisma/utils/json/PlayJson.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/SchemaMapper.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/inference/MigrationStepsInferrer.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/inference/SchemaInferrer.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/SchemaErrors.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/SchemaSyntaxValidator.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/schema/Errors.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/validation/DestructiveChanges.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/database/schema/mutations/DeployMutationSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/migration/validation/SchemaSyntaxValidatorSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/specutils/DeployTestServer.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Models.scala

Do not strictly require a relation directive to appear twice anymore. https://github.com/graphcool/prisma/issues/1569 , 
Add a validation when adding an omitted back relation later. (If it's a to one relation the omitted side can only be in one relation in existing data.) 
Add an error if we can not determine which relation operations to take after a schema change. Add a hint to provide relation directives or advance in steps. https://github.com/graphcool/prisma/issues/1836
Added tests for a case described here that was already fixed. https://github.com/graphcool/prisma/issues/1944
Fixes https://github.com/graphcool/prisma/issues/1569 , https://github.com/graphcool/prisma/issues/1836

Add validations and extra warnings to deploy when updating relations

---

docs/1.7/04-Reference/05-Prisma-Servers-&-DBs/01-Prisma-Servers/02-Docker.md

This clarifies the documentation for `docker-compose.yml` file.
`managementApiSecret` is a option under environment, as shown in the example `.yml`. 
But it was located under database->default in the description text. This PR corrects that.
Also, the remaining database default options in the text were further indended for clarification.

[doc] correct managementApiSecret placing

---

docs/1.2/04-Reference/03-Prisma-API/04-Mutations.md

Because including nested mutations within an upsert mutation is an expected, core functionality, it should be documented that this is not currently possible.

Update Upsert Docs re Nested Mutation Functionality

---

server/images/prisma-local/src/main/scala/com/prisma/local/PrismaLocalDependencies.scala
server/images/prisma-local/src/main/scala/com/prisma/local/PrismaLocalMain.scala
server/images/prisma-prod/src/main/scala/com/prisma/prod/PrismaProdDependencies.scala
server/images/prisma-prod/src/main/scala/com/prisma/prod/PrismaProdMain.scala
server/libs/sangria-utils/src/main/scala/com/prisma/sangria/utils/ErrorHandler.scala
server/prisma.yml
server/servers/deploy/src/main/scala/com/prisma/deploy/DeployDependencies.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/schema/SchemaBuilder.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/schema/types/ServerInfoType.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/ManagementServer.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/auth/AsymmetricManagementAuth.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/auth/DummyManagementAuth.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/auth/ManagementAuth.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/auth/SymmetricManagementAuth.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/database/schema/queries/ServerInfoSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/server/auth/AsymmetricManagementAuthSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/server/auth/SymmetricManagementAuthSpec.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/specutils/TestDeployDependencies.scala
server/shared-models/src/main/scala/com/prisma/shared/models/ProjectId.scala

The `cluster` endpoint was never really descriptive of what it does - managing deployments and the deployed services themselves, basically providing an overarching management API for your Prisma instance or cluster. This PR renames the `cluster` endpoint and related code to `management`.

Rename cluster to management

---

server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/database/MysqlDeployDatabaseQueryBuilder.scala
server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/impls/MysqlClientDbQueries.scala
server/connectors/deploy-connector-postgresql/src/main/scala/com/prisma/deploy/connector/postgresql/database/PostgresDeployDatabaseQueryBuilder.scala
server/connectors/deploy-connector-postgresql/src/main/scala/com/prisma/deploy/connector/postgresql/impls/PostgresClientDbQueries.scala
server/connectors/deploy-connector/src/main/scala/com/prisma/deploy/connector/DeployConnector.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/DeployingUniqueConstraintSpec.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/validation/DestructiveChanges.scala

Setting a  unique constraint will error if there are already duplicates present in the case of a field update or if a new field is required and unique since SQL will set default values for the newly required fields. This adds a validation up front and will abort the deploy already while inferring the necessary changes and not only once we change the database.
Fixes 
https://github.com/graphcool/prisma/issues/1773
https://github.com/graphcool/prisma/issues/1894
https://github.com/graphcool/prisma/issues/2011
https://github.com/graphcool/prisma/issues/2170
https://github.com/graphcool/prisma/issues/2121

Detect when setting a unique constraint is not possible

---

server/images/prisma-local/src/main/scala/com/prisma/local/PrismaLocalDependencies.scala
server/images/prisma-local/src/main/scala/com/prisma/local/PrismaLocalMain.scala
server/images/prisma-prod/src/main/scala/com/prisma/prod/PrismaProdDependencies.scala
server/images/prisma-prod/src/main/scala/com/prisma/prod/PrismaProdMain.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/DeployDependencies.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/ManagementServer.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/specutils/TestDeployDependencies.scala

This route is still (as of 1.8) deprecated and will be removed again in the future.

Reintroduce /cluster for backwards compatibility

---

docs/1.8/03-Tutorials/02-Build-GraphQL-Servers-(Development)/01-Build-a-GraphQL-Server-for-an-Existing-Prisma-Service.md

Fixes for "Build a GraphQL server for an existing Prisma service",
- Typo: "yoyur" should be "your"
- "mkdir -p my-yoga-server/src" since it is assumed we already have a directory with `prisma.yml` and `datamodel.graphql` in it, maybe just make it `mkdir -p src` instead?
- In the `.graphqlconfig.yml`, it should be `prisma: prisma/prisma.yml` instead of `prisma: prisma.yml`.
- In the `src/index.js` example, `typeDefs: './schema.graphql',` should be `typeDefs: 'src/schema.graphql',`
- In `src/schema.graphql`, `authorID` should be spelled with a lower case `d`; `authorId`.
- In `src/index.js`, `puslished` should be spelled as `published`
- "Filter posts for "GraphQL Europe" this example query should come before the `deletePost` mutation I think, else you don't have any posts to show.

Small doc fixes

---

docs/1.8/04-Reference/09-Upgrade-Guides/02-Upgrading-Prisma/02-Upgrade-to-1.7.md

I think this is just confusing. The command still works without specifying the project name, in this case `--project db`. I just pasted that command including `--project db` and got an empty `generated` folder. Now that I have removed `--project db` everything works.

Remove --project from post-hook command

---

README.md

The link to the graphql-bindings documentation 404s. I've fixed that!

Fix links to graphql-binding docs

---

docs/1.8/03-Tutorials2/03-Access-Prisma-from-Scripts/01-Access-Prisma-from-a-Node-script-using-Prisma-Bindings.md

Note that Step 1 and 3 are almost identical to [Build a GraphQL server for an existing Prisma service](https://www.prisma.io/docs/tutorials/build-graphql-servers/development/build-a-graphql-server-for-an-existing-prisma-service-ohdaiyoo6c).
Also I could not find the Quickstart file that links to the tutorials (The one that corresponds to https://www.prisma.io/docs/quickstart/). I saw it in previous versions of the docs, but not on 1.8.
I created a folder called `03-Access-Prisma-from-Scripts` inside `03-Tutorials2`. **Should I give it a different name or number?**
Another thing. I was not able to test how the article looks like in a web version of the docs. I only previewed it in a markdown previewer. **Is there a way to run the docs site locally?**

Add tutorial "Access Prisma from a Node script using Prisma Bindings"

---

server/servers/api/src/main/scala/com/prisma/api/server/ApiServer.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/server/ManagementServer.scala

Fixes an issue introduced in an earlier commit that prevents API metrics from being reported, leading to empty cloud dashboards.
Byproduct: Reduce logging verbosity on the management API.

Fix API metrics invocation

---

server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/database/PostgresApiDatabaseMutationBuilder.scala
server/connectors/api-connector-postgresql/src/main/scala/com/prisma/api/connector/postgresql/impl/PostgresDatabaseMutactionExecutor.scala
server/connectors/deploy-connector-postgresql/src/main/scala/com/prisma/deploy/connector/postgresql/database/PostgresDeployDatabaseMutationBuilder.scala

- do not set default isolation level on every transaction
- create indexes on columns of relation table
- do nothing during conflicts on relation tables

Postgres Fixes To Align to MySql behavior

---

docs/1.8/03-Tutorials2/06-Deploy-Prisma-Servers/05-AWS-Fargate.md
docs/1.9/03-Tutorials2/06-Deploy-Prisma-Servers/05-AWS-Fargate.md

AWS added additional regions to the Fargate supported list on April 26th 2018. This updates the tutorial to allow for these other regions.

Change AWS Fargate supported regions

---

cli/packages/prisma-cli-core/package.json

npm-run 5.x is broken on windows
https://github.com/timoxley/npm-run/issues/19

fix: codegen, downgrade npm-run in prisma cli

---

cli/packages/prisma-cli-core/src/commands/deploy/index.ts

This PR intends to solve https://github.com/prismagraphql/prisma/issues/2362 and related issues (https://github.com/prismagraphql/prisma/issues/2560).
Observations:-
1. Underlying packages (`graphql-cli`, `graphql-config` etc) do not write to `stderr` or emit non-zero status code on failure
1. Prisma CLI does not always check the status
1. There are (race?)-conditions that call stop function and render green unintended messages on CLI
1. We cannot aggressively fail `prisma deploy` on failing `hooks` as deployment might already be done. Need to extract the errors gracefully and communicate them back to the user

Fix hooks experience in CLI

---

docs/1.9/04-Reference/03-Prisma-API/02-Concepts.md

In the `Concepts.md` file, **JWT** has been written **JTW**. This MR fixes that word.

Fix typo in `Concepts.md` doc

---

cli/packages/prisma-cli-core/src/commands/login/login.ts

I was looking for opn issues and found this here not being used.
How about activating `--noUnusedLocals` Typescript option?
If you're OK with it I'd be willing to submit a PR turning it on and fixing where it is complaining.

remove unused import

---

cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts

I had issue introspecting a specified schema and then figured out that my selection wasn't even passed to introspect method.
I removed TODO since CLI always asks for schema, so maybe there should be no fallback to `public` or `schemas[0]` which was `public` in my case.

Use user provided schema or default to public.

---

cli/packages/prisma-cli-core/src/commands/playground/index.ts

Copied from https://github.com/facebook/create-react-app/blob/next/packages/react-dev-utils/openBrowser.js#L100
Fixes: https://github.com/prismagraphql/prisma/issues/2592
Related to: https://github.com/prismagraphql/prisma/pull/2596

Fix playground crashing on chromeos

---

cli/packages/prisma-cli-core/src/commands/deploy/index.ts
cli/packages/prisma-yml/src/Environment.ts

Fixes https://github.com/prismagraphql/prisma/issues/2480

fix: offline deploy by moving network error behind debug flag

---

docs/1.11/06-GraphQL-Ecosystem/01-GraphQL-Yoga/01-Overview.md

At https://www.prisma.io/docs/graphql-ecosystem/graphql-yoga/overview-chaha122ho/#quickstart-(hosted-demo), the link to examples is broken in
> To get started with `graphql-yoga`, follow the instructions in the READMEs of the **examples**.

docs(graphql-yoga overview): fix examples link

---

cli/packages/prisma-cli-core/src/commands/import/Validator.ts

Do not check all scalar fields in one NDF list JSON object. This is by design. 
Fixes https://github.com/prismagraphql/prisma/issues/2731

fix: NDF validator, do not check all required scalar lists

---

cli/packages/prisma-cli-engine/src/Dispatcher/Dispatcher.ts

@timsuchanek - The plugin manager uses cached topics and still yields the command `cluster`. I already tried the `GRAPHCOOL_CLI_CLEAR_CACHE` environment variable. 
This PR is a hot fix to deprecate the cluster command. We can work on finding out the actual cause of this issue later. 
The same issue is not observed for the `local` command. 
Finally, fixes https://github.com/prismagraphql/prisma/issues/2666

fix: deprecate cluster command

---

docs/1.10/03-Tutorials2/02-Build-GraphQL-Servers/02-Auth/01-Permissions.md

When I run the command:
`graphql create permissions-example --boilerplate node-advanced`
I'm not prompted to choose a public endpoint, but rather given one like so:
```
Your Prisma GraphQL database endpoint is live:
HTTP:  https://eu1.prisma.sh/public-example-123/permissions-example/dev
WS:    wss://eu1.prisma.sh/public-example-123/permissions-example/dev
```

Not prompted, given endpoint

---

docs/1.14/04-Reference/03-Prisma-API/04-Mutations.md

Fixed minor typo and object field reference at:
https://docs-beta.prisma.io/1.13/use-prisma-api/api-reference/mutations-qwe2/#scalar-list-mutations

Fix doc typos under api/mutations/scalar_list section.

---

cli/packages/prisma-cli/package.json
cli/yarn.lock

Current use case is for publishing on brew. Manually publishing the CLI has the following steps:-
⇒ Bump version in `package.json` for `prisma-cli` to whichever version we want to publish
⇒ Run `npm run package`
⇒ Follow [http://octavore.com/posts/2016/02/15/distributing-go-apps-os-x](http://octavore.com/posts/2016/02/15/distributing-go-apps-os-x)
⇒ Upload to Prisma S3 - `homebrew-prisma` bucket
⇒ Create a PR with new S3 URL, hash and version in [https://github.com/prisma/homebrew-prisma](https://github.com/prisma/homebrew-prisma)
⇒ `brew tap prisma/prisma`
⇒ `brew install prisma`

feat(package): add pkg to scripts

---

docs/1.15/get-started/01-setting-up-prisma-existing-database-a003.mdx

Remove speech marks `'` around `__YOUR_POSTGRES_PORT__` because it suggests that the port value should be enclosed in single quotes.

Update 01-setting-up-prisma-existing-database-a003.mdx 

---

docs/1.13/03-Tutorials2/06-Deploy-Prisma-Servers/06-Zeit-Now-and-Google-Cloud-SQL.md

Updated the docs to use Zeit Now's docker build v1, as v2 has a build limit of 100mb, and therefore can't deploy the Prisma server (as it has a build size of about 117.5M). 
Have simply added the features > cloud flag: v1 value to the example now.json.

Update Zeit Now & Cloud SQL to use Zeit cloud v1

---

server/servers/api/src/main/scala/com/prisma/api/schema/InputTypesBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/schema/InputTypesSchemaBuilderSpec.scala

We now generate different input types for nested mutations depending on whether the child in a relation is required on the parent or not. 
Fixes https://github.com/prisma/prisma/issues/3051

[BREAKING] Generate different inputtypes for toOneRequired and toOneOptional

---

server/servers/api/src/main/scala/com/prisma/api/server/ApiServer.scala
server/servers/api/src/main/scala/com/prisma/util/env/EnvUtils.scala

Slow queries will now be logged if the correct env vars are set.
`SLOW_QUERIES_LOGGING=TRUE`
`SLOW_QUERIES_LOGGING_THRESHOLD=1000`
The second one is optional, the default value is 1000ms.

[WIP] Set up optional slow query logging

---

server/connectors/api-connector-mysql/src/main/scala/com/prisma/api/connector/mysql/MySqlDatabasesFactory.scala
server/connectors/deploy-connector-mysql/src/main/scala/com/prisma/deploy/connector/mysql/MysqlInternalDatabaseDefs.scala

SSL already works for out PostgreSQL connector. This PR allows Prisma to connect to MySQL using SSL (prominently used on Azure by default).
Related: https://github.com/prisma/prisma/issues/2116

Fix MySql not honoring SSL config setting.

---

docs/1.17/get-started/02-change-data-model-c001.mdx

Fixes: #3107 
Previous Example Code Read:
```
// Create a new user with a new post
const newUser = await prisma
.createUser({
name: "Bob"
posts: {
create: {
title: "The data layer for modern apps",
}
},
})
console.log(`Created new user: ${newUser.name} (ID: ${newUser.id})`)
```
There should be a comma after name: "Bob"
```
// Create a new user with a new post
const newUser = await prisma
.createUser({
name: "Bob",
posts: {
create: {
title: "The data layer for modern apps",
}
},
})
console.log(`Created new user: ${newUser.name} (ID: ${newUser.id})`)
```

Add comma causing bug in example code

---

docs/1.17/run-prisma-server/authentication-and-security-kke4.mdx

As shown in #3145, there is a documentation issue for the server jwt.
The documentation was using `target: "*"` to allow access to every services. However, it should be `target: "*/*"`. This PR corrects the documentation.

Change documentation for correct target wildcard in jwt

---

server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/NodeActions.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/database/ScalarListActions.scala
server/connectors/api-connector-jdbc/src/main/scala/com/prisma/api/connector/jdbc/impl/ManyMutactionInterpreters.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeActions.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/ApiMutactionResult.scala
server/servers/api/src/main/scala/com/prisma/api/mutations/DeleteMany.scala
server/servers/api/src/main/scala/com/prisma/api/mutations/UpdateMany.scala

We now fetch the id's of nodes to update up front using the provided filter and use the id's from then on. This is a change from fetching nodes by the provided filters twice.

Update many improvement

---

cli/packages/prisma-cli-core/src/commands/init/index.ts
cli/packages/prisma-cli/package.json
cli/packages/prisma-cli/scripts/cp-assets.sh

Fixes https://github.com/prisma/prisma/issues/3150
1. Copy required assets to `dist` before packaging
1. Separate codepath for copying assets to user land FS because https://github.com/zeit/pkg/issues/420

fix(brew): asset bundling

---

docs/1.17/prisma-client/api-reference/writing-data-JAVASCRIPT-rsc6.mdx

Small typo/grammar correction.

Fix Typos in Prisma Client Docs

---

server/servers/api/src/main/scala/com/prisma/api/import_export/BulkExport.scala
server/servers/api/src/test/scala/com/prisma/api/import_export/ListValueImportExportSpec.scala

Fixes https://github.com/prisma/prisma/issues/3168
This is changing the output format when exporting json lists. But the old output format was not being accepted by the CLI validation anyways.

[BREAKING][WIP] Remove Json List Stringification

---

cli/packages/prisma-generate-schema/package.json

Having these types pulled in makes prisma unusable with something like mocha.
All other prisma packages have jest in dev rather than main dependencies.
Example errors:
```
Variable 'beforeEach' must be of type 'Lifecycle', but here has type 'HookFunction'
Variable 'it' must be of type 'It', but here has type 'TestFunction'
```

Move @types/jest to devDependencies

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/NestedDatabaseMutactionInterpreter.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/impl/CreateNodeInterpreters.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/impl/UpdateNodeInterpreters.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/impl/mutactions/ModelMutactionInterpreters.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/impl/mutactions/MongoAnyMutactionInterpreter.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/MongoBug1.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Field.scala

only create collections for non-embedded models,
pass on childResults from nested mutations,
add tests for mixed embedded / join

Mongo Bug Fixes

---

cli/packages/prisma-cli-core/src/commands/deploy/deploy.ts
cli/packages/prisma-cli-core/src/commands/init/index.ts

Fixes https://github.com/prisma/prisma/issues/3199
`generate` so that the client is already initially generated
`generated/prisma-client/`:
```yml
generate:
- generator: javascript-client
output: ./generated/prisma-client/
```

feat(client): init generate workflow

---

client/src/index.ts
client/src/utils/index.ts

Remove because it is schema delegation and we use prisma-binding for
that
Supersedes this PR: https://github.com/prisma/prisma/pull/3214
Detailed answer to why:
https://www.prisma.io/forum/t/help-understanding-prisma-clients-value-proposition/4394/17?u=divyendu_singh

fix(client): remove forwardTo

---

docs/1.18/data-model-and-migrations/data-model-knul.mdx

I was having a hard time generating the graphql schema from the prisma service. I am new in graphql and did not now [that according the specification the property name is "projects"](https://github.com/prisma/graphql-config/blob/master/specification.md), but in the example it says  "project".
Hope it helps newbies like me 😄

Adding missing "s" in graphql config file

---

docs/1.18/prisma-client/basic-data-access/reading-data-JAVASCRIPT-rsc2.mdx

In the example the code is:
```js
const linksBeforeChristmas = await prisma
.links({
where: {
createdAt_lt: "2017-12-24" 
}
})
```
But the description says: **Fetch links created before December 24, 2018:**

Fixed example for Basic filters for lists

---

cli/packages/prisma-cli-core/src/commands/init/index.ts
cli/yarn.lock

fixes #3328 
still using `spawnSync` as I don't know what was meant by "the programmatic implementation that runs the command directly without spawn" from the issue

fix 3328: change directory before automatically generating client

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/NodeManyQueries.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/RelationActions.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/database/ValidationActions.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/extensions/MongoExtensions.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/impl/DeleteNodeInterpreters.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/impl/NestedConnectInterpreter.scala
server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/impl/NestedRelationInterpreterBase.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/MongoPrototypingSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/nestedMutations/nonEmbeddedToEmbedded/EmbeddedNestedCreateMutationInsideCreateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/nestedMutations/nonEmbeddedToEmbedded/EmbeddedNestedDeleteMutationInsideUpdateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/nestedMutations/nonEmbeddedToEmbedded/EmbeddedNestedUpdateMutationInsideUpdateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/nestedMutations/nonEmbeddedToEmbeddedToNonEmbedded/UpdateWithEmbeddedNestedCreateMutationInsideCreateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/nestedMutations/nonEmbeddedToEmbeddedToNonEmbedded/UpdateWithEmbeddedNestedCreateMutationInsideUpdateSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/nonEmbedded/nestedMutations/SchemaBase.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Schema.scala

We now validate relation Ids we find since they might be dangling pointers due to missing foreign key relations.

Mongo testing for embedded relations

---

docs/1.10/03-Tutorials2/06-Deploy-Prisma-Servers/05-AWS-Fargate.md
docs/1.11/03-Tutorials2/06-Deploy-Prisma-Servers/05-AWS-Fargate.md
docs/1.12/03-Tutorials2/06-Deploy-Prisma-Servers/05-AWS-Fargate.md
docs/1.13/03-Tutorials2/06-Deploy-Prisma-Servers/05-AWS-Fargate.md
docs/1.14/03-Tutorials2/06-Deploy-Prisma-Servers/05-AWS-Fargate.md
docs/1.18/data-model-and-migrations/data-model-knul.mdx
docs/1.18/run-prisma-server/authentication-and-security-kke4.mdx
docs/1.8/03-Tutorials2/06-Deploy-Prisma-Servers/05-AWS-Fargate.md
docs/1.9/03-Tutorials2/06-Deploy-Prisma-Servers/05-AWS-Fargate.md

As pointed out in this issue, the AWS Fargate tutorial uses MANAGEMENT_API_SECRET, where it should use PRISMA_MANAGEMENT_API_SECRET. This PR amends this in all of the Fargate tutorials.

Update prisma management api secret

---

server/servers/api/src/main/scala/com/prisma/api/import_export/BulkImport.scala
server/servers/api/src/main/scala/com/prisma/api/import_export/GCValueJsonFormatter.scala

Throw a proper error if field type of an import row does not match the defined type
Fixes https://github.com/prisma/prisma/issues/2648

Improve Import Error Message

---

server/servers/api/src/main/scala/com/prisma/api/schema/InputTypesBuilder.scala
server/servers/api/src/test/scala/com/prisma/api/schema/InputTypesSchemaBuilderSpec.scala
server/servers/api/src/test/scala/com/prisma/api/schema/MutationsSchemaBuilderSpec.scala

since we were already sometimes generating the first name for other use cases

Change UpdateManyInput to UpdateManyMutationInput 

---

client/src/Client.ts

Fixes: https://github.com/prisma/prisma/issues/3248
- Prefix internal `Client` fields with `_` as to prevent naming collisions from the callers schema

Underscore client internals as to not clash with downstream schemas

---

client/src/codegen/flow-client.ts

In [Flow strict mode](https://flow.org/en/docs/strict/) no `any` types are allowed. This switches all `any` types to be [`mixed` types instead](https://flow.org/en/docs/types/mixed/), which should have the same behaviour in practice (allowing any input) but strict mode supported.

Make flow typings compatible with flow strict mode

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/MongoDatabasesFactory.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/MongoInternalDatabaseDefs.scala
server/libs/prisma-config/src/main/scala/com/prisma/config/ConfigLoader.scala

* ssl is now optional when you provide a db
* you can now choose the protocol and use a specific db without mongo+srv

Mongo Config Changes

---

docs/1.21/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4.mdx

Looks like there is an extra `.` in the link that was breaking it. This should fix the link to the Client docs.

Fix link to Prisma Client docs

---

docs/1.20/get-started/03-build-rest-apis-with-prisma-TYPESCRIPT-t202.mdx

Express and Body Parser don't have default exports, so to use them within Typescript you need to use the `import * as` syntax.

Change import for express and body-parser

---

server/shared-models/src/main/scala/com/prisma/shared/models/Model.scala

the dummyfield should not have the IdBehavior, otherwise its name always gets rewritten to _id in filters
Fixes https://github.com/prisma/Mongo-Connector-Preview/issues/13

Fix error in Mongo Join relations

---

server/connectors/api-connector-mongo/src/main/scala/com/prisma/api/connector/mongo/impl/MongoDatabaseMutactionExecutor.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/ApiConnector.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/ApiMutaction.scala
server/connectors/api-connector/src/main/scala/com/prisma/api/connector/ApiMutactionResult.scala
server/servers/api/src/main/scala/com/prisma/api/mutations/Create.scala
server/servers/api/src/main/scala/com/prisma/api/mutations/Update.scala
server/servers/api/src/main/scala/com/prisma/api/mutations/Upsert.scala

Fixes a bug where nested mutations that had exactly the same payload were sometimes not executed correctly

Mongo similar nested mutations bug

---

cli/packages/prisma-datamodel/__tests__/renderer/base.ts
cli/packages/prisma-db-introspection/src/__tests__/document/data/simpleRelational.ts
cli/packages/prisma-db-introspection/src/__tests__/document/data/webshop.ts
cli/packages/prisma-db-introspection/src/databases/document/relationResolver.ts

Added `relation(link: INLINE)` directive for relations.
Multi-Relations are now inferred correctly.
Related to #3529

Fixes related to relations

---

docs/1.17/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4.mdx
docs/1.18/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4.mdx
docs/1.19/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4.mdx
docs/1.20/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4.mdx
docs/1.21/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4.mdx
docs/1.22/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4.mdx
docs/1.23/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4.mdx

The document refers to 'subsribe' instead of 'subsribe' in several
places. This commit fixes that.

Fixed typo in 'subscribe'.

---

server/connectors/deploy-connector-jdbc/src/main/scala/com/prisma/deploy/connector/jdbc/database/RelationMutactionInterpreters.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/impl/mutactions/MongoAnyMutactionInterpreter.scala
server/connectors/deploy-connector-mongo/src/main/scala/com/prisma/deploy/connector/mongo/impl/mutactions/RelationMutactionInterpreters.scala
server/connectors/deploy-connector/src/main/scala/com/prisma/deploy/connector/DeployMutaction.scala
server/connectors/deploy-connector/src/main/scala/com/prisma/deploy/connector/MigrationStepMapperImpl.scala
server/servers/api/src/test/scala/com/prisma/api/ApiTestDatabase.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/MongoFilterPerformanceSpec.scala
server/servers/api/src/test/scala/com/prisma/api/mutations/embedded/MongoPrototypingSpec.scala

Relation indexes were only being generated correctly for the test setup running data model v1. This adds them when running data model v2.

Relation indexes for the Mongo connector

---

cli/packages/prisma-cli-engine/src/Client/Client.ts

I used the following Vagrant file to create a browser-less environment on mac
```ruby
Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/xenial64"
config.vm.synced_folder "/Users/divyendusingh/Documents/projects/graphcool/prisma", "/home/vagrant/prisma"
config.vm.synced_folder ".", "/home/vagrant/prisma-3205"
config.vm.provision :shell, :path => "bootstrap.sh"
end
```
```sh
#!/usr/bin/env bash
curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
sudo apt-get install -y nodejs
```

fix(login): support login in browser-less environment

---

cli/packages/prisma-cli-core/src/commands/deploy/deploy.ts

Fixes https://github.com/prisma/prisma/issues/3596
Although, `prisma generate` runs after `prisma init` and after this https://github.com/prisma/prisma/issues/3579, it will run after `prisma deploy` as well. 
If generation is the only use case, then is this still needed? 
Update: still needed, as the datamodel can be changed between init and deploy.

fix(hook): run post deploy hooks before seeding

---

cli/packages/prisma-cli/package.json
cli/packages/prisma-cli/src/index.ts

Fixes https://github.com/prisma/prisma/issues/2308
Here is what this PR does:- 
1. Throw and error and exit in place of throwing a warning and continue as warning route still yields the error - `TypeError: url_1.URL is not a constructor` which is confusing. 
2. Remove the warning around node versions `8.0.0` and `8.1.0`. I am not sure about the reason they were in place originally but I tried most commands with them and they work fine now.

fix(node): handle node 6 more gracefully

---

cli/packages/prisma-cli-core/src/commands/seed/Seeder.ts
cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts

Fixes https://github.com/prisma/prisma/issues/1867
This PR splits a GraphQL document with multiple operation into multiple GraphQL documents and then executes them serially.

fix(seed): support seeding based on multiple operations

---

cli/packages/prisma-datamodel/__tests__/renderer/baseV2.ts
cli/packages/prisma-datamodel/src/datamodel/renderer/index.ts
cli/packages/prisma-datamodel/src/datamodel/renderer/relationalRendererV2.ts

This adds a new beta flag to the factory method for creating datamodel renderers: 
```
export default abstract class Renderers {
public static create(databaseType: DatabaseType, enableBeta: boolean = false) : Renderer 
}
```

Add support for datamodel V2 rendering

---

cli/packages/prisma-client-lib/src/Client.ts

Fixes https://github.com/prisma/prisma/issues/3732
Here are the snapshots after this fix, all snapshots are taken after running: 
```
ab -c 10 -n 10000 http://localhost:8888/
```
Trial 1:- 
Trial 2:-
We can observe that memory is not shooting up anymore. 
Reference: https://marmelab.com/blog/2018/04/03/how-to-track-and-fix-memory-leak-with-nodejs.html

fix(client): release memory after instruction processing

---

server/connectors/deploy-connector-jdbc/src/main/scala/com/prisma/deploy/connector/jdbc/database/JdbcDeployDatabaseMutationBuilder.scala
server/integration-tests/integration-tests-mysql/src/test/scala/com/prisma/integration/RenamingWithExistingDataSpec.scala

* use renameTable to rename scalarListTables since it already correctly qualifies table names for MySQL
* add test case
* Fixes https://github.com/prisma/prisma/issues/3924

MySQL Rename Table Fix

---

docs/1.25/releases-and-maintenance/features-in-preview/mongodb-b6o5.mdx

The most nitpicky of commits, fixes `yopu` to `you`

Fix typo in mongodb-b6o5.mdx

---

docs/1.24/datamodel-and-migrations/datamodel-MONGO-knun.mdx

Fixed typo in Prisma Doc

---

server/images/prisma-local/src/main/scala/com/prisma/local/PrismaLocalDependencies.scala
server/images/prisma-prod/src/main/scala/com/prisma/prod/PrismaProdDependencies.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/migrator/AsyncMigrator.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/migrator/DeploymentSchedulerActor.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/migrator/ProjectDeploymentActor.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/schema/mutations/DeployMutation.scala

The invalidation was published before the migration was actually applied. This was uncovered by the new schema polling feature in the Playground.

Bugfix: schema must be invalidated after migration is applied and not when the migration is scheduled

---

cli/packages/prisma-client-lib/src/codegen/generators/go-client.ts

GraphQL specifies Float to be double precision.
Closes #3745

Map Float to float64

---

cli/packages/prisma-cli-core/src/commands/delete/index.ts

Fixes https://github.com/prisma/prisma/issues/3964
We have the following scenarios now:-
`message` in below context means: `Deleting service x&y from local Xms`
Service exists
1. `prisma delete -f` deletes the service and writes `message` to console, exit code 0. 
1. `prisma delete` asks for confirmation, deletes the service and writes `message` to console, exit code 0. 
Service does not exist
1. `prisma delete -f` deletes the service and writes `message` to console, exit code 0 (the only code path changed by this PR, not throwing anymore)
1. `prisma delete` asks for confirmation, deletes the service and writes `message` to console, exit code 0 [This PR does not change this exit code, it was always 0].

fix(delete): force delete behavior

---

docs/1.26/understand-prisma/prisma-vs-traditional-orms/prisma-vs-mongoose-ys8c.mdx

This is a quick, 1-letter typo fix.
- docs/1.26/understand-prisma/prisma-vs-traditional-orms/prisma-vs-mongoose-ys8c.mdx

Typo fix in prisma-vs-mongoose-ys8c.mdx

---

cli/packages/prisma-cli/package.json

These URLs are shown in `yarn outdated`. This is a PR to `alpha` since it's related to the CLI package.

Update project URLs in CLI package.json

---

docs/1.24/prisma-cli-and-configuration/prisma-yml-5cy7.mdx

The URL is still pointing to the old repo.
Correcting that.
PS Is this the right `base` or should it also target `alpha`?

Fix broken URL in docs/cli#seed

---

docs/1.8/03-Tutorials2/01-Setup-Prisma/02-Create-New-DB/01-MySQL.md

Docker-Compose Reference URL was earlier pointing to localhost:3000, fixed to point to the correct alias

Fixed Docker Compose Link

---

docs/1.18/get-started/03-build-rest-apis-with-prisma-e002.mdx

Fixes
```
/Users/michael/github/prisma-test/index.js:2
const app = express()
^
ReferenceError: express is not defined
```

Corrected express instantiation in Docs

---

docs/1.19/prisma-client/features/realtime-JAVASCRIPT-rsc8.mdx

Renamed the Prisma client instance from `db` to `prisma` to maintain consistency throughout the docs.

update example code

---

docs/1.20/prisma-cli-and-configuration/prisma-yml-5cy7.mdx

needs to contains at least two properties
to
needs to contain at least two properties

Grammatical Error

---

docs/1.23/prisma-cli-and-configuration/data-import-and-export-jsw9.mdx

The -e is used for env vars. --path or -p are the correct arguments for the `prisma export` command

Path switch was wrong

---

docs/1.23/get-started/03-build-graphql-servers-with-prisma-GO-g201.mdx

Ran into this issue: exec plan failed: unable to resolve package for hello-word/prisma.User: cannot find package "hello-word/prisma"
By adding generated to the given path, it does work.

Fix path to generated prisma.go

---

server/libs/prisma-config/src/main/scala/com/prisma/config/ConfigLoader.scala
server/libs/prisma-config/src/test/scala/com/prisma/auth/ConfigLoaderSpec.scala
server/shared-models/src/main/scala/com/prisma/shared/models/Project.scala

* use the database for project.dbName if one is specified.
* only allow database + schema for Postgres
* do not allow schema only, just database only
Fixes https://github.com/prisma/prisma/issues/4040 https://github.com/prisma/prisma/issues/4050

Existing DB bug

---

cli/packages/prisma-cli-core/src/commands/introspect/introspect.ts
cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts

Fixes the issues outlined in #4081
The datamodel always needs to be normalized, also when no existing datamodel is given.

Fixes 4081

---

server/prisma-rs/prisma-models/src/field.rs
server/prisma-rs/prisma-models/src/field/relation.rs
server/prisma-rs/prisma-models/src/field/scalar.rs
server/prisma-rs/prisma-models/src/model.rs
server/prisma-rs/prisma-models/src/project.rs
server/prisma-rs/prisma-models/src/relation.rs
server/prisma-rs/prisma-models/src/schema.rs
server/prisma-rs/src/protobuf/input/get_node_by_where.rs
server/prisma-rs/src/protobuf/input/get_nodes.rs

This PR does the following things:
* it removes obsolete fields that we won't need anymore
* schema must not have project as a parent because we have cases where we have a schema but not a project (in the migration engine)
* come up with a suggestion to ease working with parent child relationships (see my comment in the changed files for an example)

models cleanup

---

cli/packages/prisma-cli-engine/src/Client/Client.ts

Missing management secret:
Incorrect management secret:

fix(cli-docs): update wording for management secret issues

---

server/images/prisma-native/src/main/resources/playground.html
server/libs/sangria-server/src/main/resources/admin.html
server/libs/sangria-server/src/main/resources/playground.html
server/libs/sangria-server/src/main/scala/com/prisma/sangria_server/AkkaHttpSangriaServer.scala
server/libs/sangria-server/src/main/scala/com/prisma/sangria_server/BlazeSangriaServer.scala
server/libs/sangria-server/src/main/scala/com/prisma/sangria_server/SangriaServer.scala

Adds path suffix `_admin` to access Prisma Admin on `/service/stage`. E.g.
- `/_admin` (implicit `/default/default/_admin`)
- `/service/_admin` (implicit `/service/default/_admin`)
- `/service/name/_admin`
are all valid paths to access Prisma Admin.

Add prisma admin routes

---

cli/packages/prisma-cli-core/src/commands/init/init.ts
cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts

Fixes https://github.com/prisma/prisma/issues/4072
1. Lazy create directory
2. Silently catch exceptions to handle missing directory case but emit
handled errors in debug mode

fix(init-directory): lazy create directory

---

cli/packages/prisma-client-lib/src/Client.ts

Fixes https://github.com/prisma/prisma/issues/3950
This PR adds the `reconnect` flag to the subscription client. This [comment](https://github.com/prisma/prisma/issues/3950#issuecomment-460244341) suggests that `inactivityTimeout` should not close the connection when there are active subscriptions.

fix(client-subscriptions): add reconnect option

---

server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/DataModelValidatorImpl.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/DeployResults.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/LegacyDataModelValidator.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/migration/validation/GeneralDataModelValidatorSpec.scala

* add a datamodel validation for type names Prisma uses in the schema
* these are: `Mutation`, `Query`, `Subscription`, `Node`, `PageInfo`, `BatchPayload`
* Additionally users could also face errors if they define a typeName and a second typeName that equals a name Prisma would derive from the first i.e. `A` and `ACreateInput`
Fixes https://github.com/prisma/prisma/issues/4226

Validate use of reserved type names in datamodel

---

server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/DeployResults.scala
server/servers/deploy/src/main/scala/com/prisma/deploy/migration/validation/directives/RelationDirective.scala
server/servers/deploy/src/test/scala/com/prisma/deploy/migration/validation/GeneralDataModelValidatorSpec.scala

* implementing Cascading Deletes using transactions like we do on the SQL connectors creates concurrency errors
* we therefore can not enable this feature at this time
* add a validation during deploy that errors if Mongo defines onDelete argument
Fixes https://github.com/prisma/prisma/issues/3796

Mongo Cascading Delete Validation

---

cli/packages/prisma-cli-core/src/commands/delete/index.ts
cli/packages/prisma-cli-core/src/commands/deploy/deploy.ts
cli/packages/prisma-cli-core/src/commands/export/index.ts
cli/packages/prisma-cli-core/src/commands/import/index.ts
cli/packages/prisma-cli-core/src/commands/info/index.ts
cli/packages/prisma-cli-core/src/commands/init/init.ts
cli/packages/prisma-cli-core/src/commands/introspect/introspect.ts
cli/packages/prisma-cli-core/src/commands/seed/seed.ts
cli/packages/prisma-cli-engine/src/Command.ts
cli/packages/prisma-cli-engine/src/commands/version.ts

Implements
https://github.com/divyenduz/rfcs/blob/cli-server-sync/text/0000-cli-server-sync.md
Two concerns that need to be reviewed: 
1. This pollutes the `Command` class to be aware of cluster (by initiating one), which might be ok since some commands now rely on getting actual server version. 
1. `await cmd.definition.load(cmd.flags, envFile)` in `areServerAndCLIInSync ` would load the environment twice for some command, making them further slow https://github.com/prisma/prisma/issues/3547

feat(warning): when server and CLI are not in sync

---

cli/packages/prisma-db-introspection/src/__tests__/document/mongo/models.ts
cli/packages/prisma-db-introspection/src/databases/document/relationResolver.ts

The `data` in `data[field.name]` in line `182` is `null` for a particular customer's data. In place of adding a null check, I wanted to try the approach of being more forgiving while creating a datamodel and explore what went wrong via debug. 
Feedback requested on this PR. 
Update: It is `null` because of an embedded type being `null`. Added a test case to validate this fix.

fix(mongo): more forgiving introspection

---

server/servers/api/src/main/scala/com/prisma/api/import_export/GCValueJsonFormatter.scala
server/servers/api/src/test/scala/com/prisma/api/import_export/BulkImportSpec.scala

* allows imports into data models that are missing explicit createdAt, updatedAt fields from versions that exported the implicit fields

ignore values for CreatedAt, UpdatedAt if they are not on the model

---

docs/1.19/prisma-graphql-api/reference/raw-database-access-qwe4.mdx
docs/1.27/prisma-server/authentication-and-security-kke4.mdx

I couldn't build the docs locally without this change.

Docs: add missing mdx import

---

server/servers/api/src/test/scala/com/prisma/api/ApiTestServer.scala

This change is required because of two things:
1. There are now several parse-attempts of multiple datamodel files.
This just generally adds overhead when starting a prisma server
2. The code is being run in `Debug` mode which generally is a good
idea, but in this case means startup is much slower.
Ideally we want to change the structure of how tests are run anyway
but for now this change should do. It's just long enough for the
server to initialise in most cases. Do be aware that this number might
have to be adjusted in the future.

Increasing test-server startup delay

---

cli/packages/prisma-datamodel/package.json
cli/packages/prisma-db-introspection/src/databases/document/documentConnectorBase.ts
cli/packages/prisma-db-introspection/src/databases/relational/mysql/mysqlConnector.ts
cli/packages/prisma-db-introspection/src/databases/relational/postgres/postgresConnector.ts
cli/packages/prisma-db-introspection/src/databases/relational/relationalConnector.ts

* Fetching of column comments now happens in one query per table.
* Speed for discourse from 127s to 22s.
* Problem is high round-trip time x lots of queries.
* Further optimization should attempt to reduce the number of queries made.

CLI/introspection:

---

server/prisma-rs/query-engine/core/src/builders/mutations/ast.rs
server/prisma-rs/query-engine/core/src/builders/mutations/look_ahead.rs
server/prisma-rs/query-engine/core/src/builders/mutations/root.rs
server/prisma-rs/query-engine/core/src/executor/mod.rs
server/prisma-rs/query-engine/core/src/executor/pipeline.rs
server/prisma-rs/query-engine/core/src/executor/write.rs
server/prisma-rs/query-engine/core/src/lib.rs

When traversing a mutation tree, sometimes the order of creation has
to be flipped to align with how relation fields are expressed in the
database. This PR implements this feature, allowing mutations to
succeed that rely on required relation fields on objects that don't
exist yet.
It adds the `LookAhead` module which performs both merge and split
operations on the tree, as well a the `DependentSet` type which can
either express a single mutation tree, or a "dependent set" (😉) of
mutations that need to be executed in order. The convenience function
`LookAhead::eval_partial` then injects results into the base mutation.

Implementing order-reversal mutations (dependent mutations)

---

cli/packages/prisma-db-introspection/src/__tests__/mysql/blackbox/withoutExistingSchema/__snapshots__/migrationTable.test.ts.snap
cli/packages/prisma-db-introspection/src/__tests__/mysql/blackbox/withoutExistingSchema/migrationTable.test.ts
cli/packages/prisma-db-introspection/src/__tests__/postgres/blackbox/withoutExistingSchema/__snapshots__/migrationTable.test.ts.snap
cli/packages/prisma-db-introspection/src/__tests__/postgres/blackbox/withoutExistingSchema/migrationTable.test.ts
cli/packages/prisma-db-introspection/src/databases/relational/mysql/mysqlIntrospectionResult.ts
cli/packages/prisma-db-introspection/src/databases/relational/postgres/postgresIntrospectionResult.ts

Takes care of https://github.com/prisma/prisma2/issues/78.

Introspection now ignores _Migration table at database level.

---

server/prisma-rs/query-engine/connectors/sql-connector/src/database/sqlite.rs
server/prisma-rs/query-engine/prisma/src/exec_loader.rs

File paths should be taken from the connector for proper parsing.

Get the sqlite file path from the connector

---

server/prisma-rs/libs/prisma-common/src/logger.rs

Increases the slog channel size from 128 to 1024 to prevent:
```Error: slog-async: logger dropped messages due to channel overflow```
Default size can be found here:
https://docs.rs/slog-async/2.3.0/src/slog_async/lib.rs.html#236

Increase slog channel size

---

server/servers/api/src/main/scala/com/prisma/subscriptions/SubscriptionExecutor.scala
server/servers/subscriptions/src/test/scala/com/prisma/subscriptions/specs/SubscriptionFilterSpec.scala

Fixes https://github.com/prisma/prisma/issues/4772

Subscription Lookup Should Use Alias if Specified

---

server/prisma-rs/Cargo.lock
server/prisma-rs/Cargo.toml
server/prisma-rs/libs/database-introspection/Cargo.toml
server/prisma-rs/libs/database-introspection/src/lib.rs
server/prisma-rs/libs/database-introspection/src/mysql.rs
server/prisma-rs/libs/database-introspection/src/postgres.rs
server/prisma-rs/libs/database-introspection/src/sqlite.rs
server/prisma-rs/libs/database-introspection/tests/introspection_connection_tests.rs

Implement MySQL introspection in Rust. Please wait until #4792 is merged.
Please note that I'm depending on a version of the Barrel crate from my own GitHub repo, since I had to make fixes. I'm not sure if we should keep using GitHub for the dependency or publish our own crate.

Rust MySQL inspection

---

server/prisma-rs/Cargo.lock
server/prisma-rs/libs/datamodel/Cargo.toml
server/prisma-rs/libs/datamodel/src/ast/parser/datamodel.pest
server/prisma-rs/libs/datamodel/tests/end_to_end/parser_renderer_ast.rs
server/prisma-rs/libs/datamodel/tests/mod.rs
server/prisma-rs/libs/datamodel/tests/reformat/mod.rs
server/prisma-rs/libs/datamodel/tests/reformat/reformat.rs

Currently the datamodel parser panics if you add tabs, this PR fixes it.
Closes: https://github.com/prisma/prisma2/issues/327

Add support for tabs in the datamodel

---

server/prisma-rs/libs/database-introspection/src/mysql.rs
server/prisma-rs/libs/database-introspection/src/postgres.rs

Remove `println!` calls from database introspection code, we use logging instead.

Remove introspection printlns 

---

server/prisma-rs/migration-engine/connectors/sql-migration-connector/src/database_inspector/mod.rs
server/prisma-rs/migration-engine/connectors/sql-migration-connector/src/lib.rs
server/prisma-rs/migration-engine/connectors/sql-migration-connector/tests/database_inspector_tests.rs
server/prisma-rs/migration-engine/core/tests/existing_databases_tests.rs
server/prisma-rs/migration-engine/core/tests/test_harness/misc_helpers.rs

I realized that the `DatabaseInspector` trait was containing a lot of methods which were conceptually free functions, after @pimeys asked me to clean up said trait. I moved those methods into free functions in the namespace which I think is a lot simpler.

Clean DatabaseInspector trait

---

server/prisma-rs/Cargo.lock
server/prisma-rs/Cargo.toml
server/prisma-rs/libs/database-introspection/Cargo.toml
server/prisma-rs/libs/database-introspection/src/sqlite.rs
server/prisma-rs/libs/database-introspection/tests/introspection_connection_tests.rs

Add test to ensure that hyphenated table/column names are supported. I also had to patch Barrel to make this work, now using the master branch of my fork of the latter.

database-introspection: support hyphenated names

---

server/prisma-rs/libs/database-introspection/src/lib.rs
server/prisma-rs/libs/database-introspection/src/mysql.rs
server/prisma-rs/libs/database-introspection/src/postgres.rs
server/prisma-rs/libs/database-introspection/src/sqlite.rs
server/prisma-rs/libs/database-introspection/tests/introspection_connection_tests.rs
server/prisma-rs/libs/database-introspection/tests/resources/schema.json
server/prisma-rs/libs/database-introspection/tests/serialization_tests.rs

As requested by @mavilein, change field `Index::unique` to enum `Index::tpe`.

database-introspection: Change index field 'unique' to enum named 'tpe'

---

server/prisma-rs/libs/logger/src/lib.rs

Fix the following compilation failure related to a doctest:
``` 
Doc-tests logger
error[E0659]: `logger` is ambiguous (name vs any other name during import resolution)
--> /Users/arve/Projects/prisma/prisma/server/prisma-rs/libs/logger/src/lib.rs:10:9
|
10 | pub use logger::*;
|         ^^^^^^ ambiguous name
|
= note: `logger` could refer to an extern crate passed with `--extern`
= help: use `::logger` to refer to this extern crate unambiguously
note: `logger` could also refer to the module defined here
--> /Users/arve/Projects/prisma/prisma/server/prisma-rs/libs/logger/src/lib.rs:8:1
|
8  | mod logger;
| ^^^^^^^^^^^
= help: use `crate::logger` to refer to this module unambiguously
error: aborting due to previous error
```

Fix doctest compilation failure

---

README.md

This fixes the image being skewed on small screens
Before & after:
The only caveat is that it renders huge when comparing in split diff and rendered mode, which is probably okay:

docs(readme): fix image height

---

cli/packages/prisma-cli-core/src/commands/export/index.ts

As you can see in the output of `prisma export --help`, the short option `-p` is used **twice** for two different options (`--path` and `--project`).
This doesn't work obviously so this PR just removes the short option `-p` for `--project` (which is being ignored anyway).
This change should have 0 impact on the behaviour of the command. It will only affect the output of `--help`.

Remove `-p` short option for `prisma export --project`

---

cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts
cli/packages/prisma-cli-core/src/utils/__snapshots__/EndpointDialog.test.ts.snap

Fixes a small typo in `EndpointDialog.ts`. Changes text from `...connect to your your database...` to `...connect to your database...`

fix typo in packages/prisma-cli-core/src/utils/EndpointDialog.ts

---

docs/1.34/prisma-server/authentication-and-security-kke4.mdx

This file at one point incorrectly refers to the needed PRISMA_MANAGEMENT_API_SECRET env var as PRISMA_MANAGEMENT_SECRET

Fix incorrect env var reference to PRISMA_MANAGEMENT_API_SECRET

---

docs/1.28/prisma-cli-and-configuration/cli-command-reference/prisma-seed-xcv8.mdx

Without a blank line above, the markdown link does not render correctly

Fix formatting of link in seed docs

---

docs/1.34/prisma-server/authentication-and-security-kke4.mdx

**Describe the bug**
The environment variable is wrong, using the described name doesn't work and the cli will spit out an unauthorised error. 
**To Reproduce**
In your .env file declare PRISMA_MANAGEMENT_SECRET and use it in your docker.compose file.
After you build and run docker try running `prisma deploy` the result should be that you aren't authorised.
**Expected behavior**
The declared .env variable should be picked up by the prisma cli and you should be able to deploy as per usual.
**Versions (please complete the following information):**
- Connector:`Postgres:12`
- Prisma Server: 1.34.10
- Prisma CLI version: prisma/1.34.10 (windows-x64) node-v13.6.0
- OS:`Windows 10` 
**Additional context**
The described environment variable didn't work and after some research I found the correct …

Name of environment variable is wrong

---

docs/1.27/faq/index.mdx
docs/1.28/faq/index.mdx

If you visit the docs at https://www.prisma.io/docs/faq/, the link "How to keep the version of your Prisma server in sync with the Prisma CLI?" is broken.
I believe this should fix it, though I'm not familiar with how these docs are generated.

Fix link in FAQ docs
